



CREATE TABLE IF NOT EXISTS `belgisch_bier` (
  `ID` int(11) NOT NULL DEFAULT '0',
  `Naam` varchar(100) DEFAULT NULL,
  `Brouwer` varchar(100) DEFAULT NULL,
  `Type` varchar(30) DEFAULT NULL,
  `Gisting` varchar(30) DEFAULT NULL,
  `Kleur` varchar(30) DEFAULT NULL,
  `Alcoholperc` varchar(30) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Gegevens worden geëxporteerd voor tabel `belgisch_bier`
--

INSERT INTO `belgisch_bier` (`ID`, `Naam`, `Brouwer`, `Type`, `Gisting`, `Kleur`, `Alcoholperc`) VALUES
(1, 'Abondance mirabellen', 'Brouwerij de Troch', 'overige', 'spontane', 'amber', '3,5% vol.'),
(2, 'Abondance pêche', 'Brouwerij de Troch', 'overige', 'spontane', 'amber', '3,5% vol.'),
(3, 'Adler', 'Brouwerij Haacht', 'dortmunder', 'lage', 'blond EBC 10', '6,5% vol.'),
(4, 'Aerts 1900', 'Brouwerij Palm', 'overige', 'hoge met nof', 'rood-amber EBC 34', '7,4% vol.'),
(5, 'Affligem christmas', 'Brouwerij de Smedt', 'overige', 'hoge', 'bruin EBC 60', '7,0% vol.'),
(6, 'Affligem donker', 'Brouwerij de Smedt', 'dubbel', 'hoge met nof', 'bruin EBC 60', '6,5% vol.'),
(7, 'Affligem helder', 'Brouwerij de Smedt', 'overige', 'hoge met nof', 'amber EBC 19', '6,5% vol.'),
(8, 'Affligem rood', 'Brouwerij de Smedt', 'overige', 'hoge met nof', 'amber EBC 19', '6,5% vol.'),
(9, 'Affligem tripel', 'Brouwerij de Smedt', 'tripel', 'hoge met nof', 'blond EBC 13', '9,0% vol.'),
(10, 'Affligem van ''t patersvat', 'Brouwerij de Smedt', 'overige', 'hoge met nof', 'amber EBC 19', '6,5% vol.'),
(11, 'Akila pils', 'Brouwerij Louwaege', 'pilsener', 'lage', 'blond EBC 5', '5,0% vol.'),
(12, 'Alexander Rodenbach', 'Bierbrouwerij Rodenbach', 'overige', 'hoge+melkzure', 'lichtbruin EBC 40', '6,2% vol.'),
(13, 'Alken export', 'Alken-Maes (zetel Alken)', 'pilsener', 'lage', 'blond EBC 8', '4,5% vol.'),
(14, 'Allard extra', 'Brasserie Allard et Groetembril', 'saison', 'hoge met nof', 'amber', '7,0% vol.'),
(15, 'Allard extra vieille', 'Brasserie Allard et Groetembril', 'saison', 'hoge met nof', 'amber', '7,0% vol.'),
(16, 'Ambiorix dubbel', 'Brouwerij Slagmuylder', 'dubbel', 'hoge met nof', 'donkerbruin', '7,8% vol.'),
(17, 'Anglo pils', 'Alken-Maes (zetel Waarloos)', 'pilsener', 'lage', 'blond EBC 9', '4,9% vol.'),
(18, 'Anglo pils', 'Alken-Maes (zetel Alken)', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(19, 'Antiek', 'Brouwerij Isebaert', 'overige', 'hoge', 'amber', '8,0% vol.'),
(20, 'Antigoon', 'Brouwerij Isebaert', 'overige', 'hoge', 'amber', '8,0% vol.'),
(21, 'Arabier', 'De Dolle Brouwers', 'overige', '?', '?', 'Onbekend'),
(22, 'Aro pils', 'Brouwerij Haacht', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(23, 'Artevelde', 'Brouwerij L. Huyghe N.V.', 'ale', 'hoge', 'amber EBC 28', '6,7% vol.'),
(24, 'Artevelde grand cru', 'Brouwerij L. Huyghe N.V.', 'overige', 'hoge met nof', 'bruin EBC 55', '6,4% vol.'),
(25, 'Artevelde pils', 'Brouwerij L. Huyghe N.V.', 'pilsener', 'lage', 'blond EBC 10', '5,1% vol.'),
(26, 'Artois export', 'Artois (groep Interbrew)', 'pilsener', 'lage', 'blond', '5,1% vol.'),
(27, 'Artvelde grand cru op gist', 'Brouwerij L. Huyghe N.V.', 'overige', 'hoge met nof', 'bruin EBC 55', '6,4% vol.'),
(28, 'Artvelde menta', 'Brouwerij L. Huyghe N.V.', 'overige', 'lage', 'groen', '5,4% vol.'),
(29, 'Artvelde op gist', 'Brouwerij L. Huyghe N.V.', 'ale', 'hoge', 'amber EBC 28', '6,7% vol.'),
(30, 'Augustijn', 'Brouwerij Bios', 'overige', 'hoge met nof', 'amber', '8,0% vol.'),
(31, 'Augustijn grand cru', 'Brouwerij Bios', 'tripel', 'hoge met nof', 'blond', '9,0% vol.'),
(32, 'Avec les Bons Voeux de la brasserie Dupont', 'Brasserie Dupont', 'overige', 'hoge met nof', 'amber', '9,6% vol.'),
(33, 'Bacchus', 'Brouwerij Van Honsebrouck', 'Vlaamse bruine', 'hoge', 'bruin', '4,8% vol.'),
(34, 'Baf', 'Brouwerij de Smedt', 'Belgische ale', 'hoge', 'amber EBC 20', '5,0% vol.'),
(35, 'Bailus', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin EBC 44', '8,8% vol.'),
(36, 'Bakelandt', 'Brouwerij van Eecke', 'overige', 'hoge met nof', 'licht amber', '7,5% vol.'),
(37, 'Bass Old Barley Stout', 'Lamot (groep Interbrew)', 'stout', 'hoge', 'donkerbruin', '6,4% vol.'),
(38, 'Bass pale ale', 'Lamot (groep Interbrew)', 'pale ale', 'hoge', 'amber', '5,2% vol.'),
(39, 'Battin Edelpils', 'Brasserie Battin', 'pilsener', 'lage', 'blond', '4,75% vol.'),
(40, 'Battin Gambrinus', 'Brasserie Battin', 'pilsener', 'lage', 'blond', '5,8% vol.'),
(41, 'Battin Gambrinus bock', 'Brasserie Battin', 'bokbier', 'lage', 'donkerbruin', '7,0% vol.'),
(42, 'Battin Gambrinus urtyp', 'Brasserie Battin', 'pilsener', 'lage', 'blond', '6,0% vol.'),
(43, 'Bavik super pils', 'Bavik - De Brabandere', 'pilsener', 'lage', 'blond EBC 6', '4,9% vol.'),
(44, 'Belga pils', 'Brouwerij Leroy', 'pilsener', 'lage', 'blond', '5,0% vol.'),
(45, 'Belle Vue frambozen', 'Belle Vue', 'framboise', 'spontane', 'amber', '5,4% vol.'),
(46, 'Belle Vue gueuze lambic "cuvée"', 'Belle Vue', 'gueuze', 'spontane', 'amber', '5,1% vol.'),
(47, 'Belle Vue kriek lambic', 'Belle Vue', 'kriekenbier', 'spontane', 'rood', '5,2% vol.'),
(48, 'Belle Vue kriek lambic "cuvée"', 'Belle Vue', 'kriekenbier', 'spontane', 'rood', '5,2% vol.'),
(49, 'Benedict', 'Brouwerij De Kluis (groep Interbrew)', 'dubbel', 'hoge met nof', 'bruin EBC 65', '7,0% vol.'),
(50, 'Bergenbier', 'Artois (groep Interbrew)', 'pilsener', 'lage', 'blond', '5,1% vol.'),
(51, '''n Seule', 'Brouwerij Slagmuylder', 'overige', 'hoge met nof', 'lichtbruin', '6,0% vol.'),
(52, '''t Paterke Achelse Kluis', 'Brouwerij R. Gielen', 'dubbel', 'hoge met nof', 'lichtbruin', '6,0% vol.'),
(53, '203 Hamse witten', 'Brouwerij Vieille Villers', 'witbier', 'lage', 'blond', '5,3% vol.'),
(54, '406 Wuitensbier', 'Brouwerij Vieille Villers', 'dubbel', 'hoge', 'donkerbruin', '6,2% vol.'),
(55, '1664 de Kronenbourg', 'Alken-Maes (zetel Alken)', 'superpils', 'lage', 'blond EBC 10', '5,5% vol.'),
(56, 'A la ferme', 'Brouwerij Isebaert', 'overige', 'hoge', 'amber', '8,0% vol.'),
(57, 'Abbaye d''Aulne ADA 6° sur lie', 'Brouwerij de Smedt', 'overige', 'hoge met nof', 'amber EBC 19', '6,5% vol.'),
(58, 'Abbaye d''Aulne ADA 8° Selection', 'Brouwerij de Smedt', 'overige', 'hoge', 'bruin EBC 58', '8% vol.'),
(59, 'Abbaye d''Aulne ADA 10° superbe', 'Brouwerij de Smedt', 'gerstewijn', 'hoge', 'bruin EBC 58', '10% vol.'),
(60, 'Abbaye de Bonne Espérance', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'amber', '8% vol.'),
(61, 'Abbaye de Brogne Tripel sur lie', 'Brouwerij de Smedt', 'tripel', 'hoge met nof', 'blond EBC 13', '9,0% vol.'),
(62, 'Abbaye de Cambron', 'Brasserie de Silly', 'saison', 'hoge', 'amber', '5,8% vol.'),
(63, 'Abbaye de Gembloux', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'amber', '8% vol.'),
(64, 'Abbaye de la Moinette', 'Brasserie Dupont', 'overige', 'hoge met nof', 'licht amber', '8,5% vol.'),
(65, 'Abbaye de Saint-Ghislain', 'Brasserie Dupont', 'overige', 'hoge met nof', 'licht amber', '8,5% vol.'),
(66, 'Abbaye des Rocs', 'Brasserie de l''Abbaye des Rocs (Brasserie Eloir-Bertiau)', 'overige', 'hoge met nof', 'donkerbruin', '9% vol.'),
(67, 'Abbaye du Val St.-Lambert', 'Brasserie Allard et Groetembril', 'overige', 'hoge+melkzure', 'donker amber', '9,5% vol.'),
(68, 'Abdij van Steenbrugge', 'Brouwerij De Gouden Boom', 'dubbel', 'hoge met nof', 'bruin', '6,5% vol.'),
(69, 'Abdijbier Loo', 'Brouwerij Isebaert', 'tripel', 'hoge met nof', 'blond', '7,5% vol.'),
(70, 'Abondance banaan', 'Brouwerij de Troch', 'overige', 'spontane', 'amber', '3,5% vol.'),
(71, 'Abondance framboos', 'Brouwerij de Troch', 'framboise', 'spontane', 'lichtrood', '3,5% vol.'),
(72, 'Abondance kriek', 'Brouwerij de Troch', 'overige', 'spontane', 'lichtrood', '3,5% vol.'),
(73, 'Beyerd Speciaal', 'Brouwerij Sterkens', 'ale', 'hoge', 'donker amber', '6,5% vol.'),
(74, 'Beyerd speciaal 150', 'Brouwerij Sterkens', 'tripel', 'hoge', 'blond', '8,0% vol.'),
(75, 'Bezebier', 'Brouwerij Van Honsebrouck', 'overige', 'spontane', 'rood', '5,0% vol.'),
(76, 'Bécasse gueuze', 'Brabrux (Groep Belle-Vue)', 'gueuze', 'spontane', 'amber', '5,2% vol.'),
(77, 'Biermarkt super pils', 'Brouwerij Verhaeghe', 'pilsener', 'lage', 'blond', '4,0% vol.'),
(78, 'Bière de la Commanderie de piéton', 'Brasserie Allard et Groetembril', 'overige', 'hoge+melkzure', 'donker amber', '9,5% vol.'),
(79, 'Bière des Ducs Lothier', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'amber', '8,0% vol.'),
(80, 'Bière des Sorcières d''Ellezelles', 'Brasserie Voisin', 'overige', 'hoge met nof', 'licht amber', '6,8% vol.'),
(81, 'Bière du Boucanier', 'Brouwerij Bios', 'gerstewijn', 'hoge met nof', 'blond', '11,0% vol.'),
(82, 'Bière la Pax chatelet', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'amber', '8% vol.'),
(83, 'Bink', 'Huisbrouwerij Kerkom', 'overige', 'hoge met nof', 'amber', '5,5% vol.'),
(84, 'Bios export', 'Brouwerij Bios', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(85, 'Bios Vlaamse bourgogne', 'Brouwerij Bios', 'Vlaamse bruine', 'hoge met nof', 'donkerbruin', '6,0% vol.'),
(86, 'Blanch-ke', 'Brouwerij Van Honsebrouck', 'witbier', 'hoge met nof', 'blond', '5,0% vol.'),
(87, 'Block export', 'Brouwerij de Block', 'pilsener', 'lage', 'blond', '4,6% vol.'),
(88, 'Blonde des pères Abbaye d''Aulne', 'Brouwerij de Smedt', 'overige', 'hoge met nof', 'amber EBC 20', '7,5% vol.'),
(89, 'Blonde des pères Abbaye de Brogne', 'Brouwerij de Smedt', 'overige', 'hoge met nof', 'amber EBC 20', '7,5% vol.'),
(90, 'Blonde du menhir', 'Brasserie Lefèbvre', 'saison', 'hoge met nof', 'blond', '5,5% vol.'),
(91, 'Bocholter Kwik Pils', 'Brouwerij Martens', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(92, 'Bock pils', 'Brouwerij Palm', 'pilsener', 'lage', 'blond EBC 6', '5,3% vol.'),
(93, 'Bockhauser pils', 'Brouwerij Haacht', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(94, 'Bockor', 'Brouwerij Bockor', 'pilsener', 'lage', 'blond EBC 6', '5,2% vol.'),
(95, 'Bockor export', 'Brouwerij Bockor', 'pilsener', 'lage', 'blond EBC 6', '5,2% vol.'),
(96, 'Bockor pils', 'Brouwerij Bockor', 'pilsener', 'lage', 'blond EBC 6', '5,2% vol.'),
(97, 'Bokkereyer', 'Brouwerij St. Jozef', 'overige', 'lage', 'bruin EBC 40', '6,0% vol.'),
(98, 'Bokrijk tarwe beer', 'Brouwerij de Block', 'witbier', 'hoge met nof', 'blond', '5,0% vol.'),
(99, 'Bokrijks kruikenbier', 'Brouwerij Sterkens', 'tripel', 'hoge met nof', 'blond', '7,2% vol.'),
(100, 'Bolderbergs kluizenaarsbier', 'Brouwerij Sterkens', 'ale', 'hoge', 'donker amber', '6,5% vol.'),
(101, 'Bornem dubbel', 'Brouwerij Bios', 'dubbel', 'hoge met nof', 'donkerbruin', '8,0% vol.'),
(102, 'Bornem St. Bernard', 'Brouwerij Bios', 'dubbel', 'hoge met nof', 'donkerbruin', '8,0% vol.'),
(103, 'Boskeun', 'De Dolle Brouwers', 'overige', 'hoge met nof', 'amber', '8,0% vol.'),
(104, 'Bourgogne des Flandres', 'Brouwerij Verhaeghe', 'Vlaamse bruine', 'hoge', 'donkerbruin', '5,8% vol.'),
(105, 'Boxer pils', 'Brouwerij Roman', 'pilsener', 'lage', 'blond EBC 7', '5,1% vol.'),
(106, 'Brabants witbier', 'Brouwerij Palm', 'witbier', 'hoge met nof', 'blond', '5,0% vol.'),
(107, 'Brave broeder', 'Brasserie de Silly', 'saison', 'hoge', 'amber', '5,8% vol.'),
(108, 'Brigand', 'Brouwerij Van Honsebrouck', 'tripel', 'hoge met nof', 'blond', '9,0% vol.'),
(109, 'Brouwers abdijbier', 'Brouwerij de Smedt', 'dubbel', 'hoge met nof', 'bruin EBC 60', '6,5% vol.'),
(110, 'Brouwers Bier Belgisch Bier', 'Brouwerij Piedboeuf', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(111, 'Brouwmeester', 'Alken-Maes (zetel Alken)', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(112, 'Brug ale', 'Brasserie de Silly', 'Belgische ale', 'hoge', 'amber', '5,2% vol.'),
(113, 'Brugse straffe Hendrik', 'Huisbrouwerij Straffe Hendrik (groep Riva)', 'overige', 'hoge met nof', 'blond EBC 7', '5,4% vol.'),
(114, 'Bruinekuif', 'Brouwerij Verhaeghe', 'Vlaamse bruine', 'hoge', 'donkerbruin', '5,8% vol.'),
(115, 'Brunehaut 8', 'Brasserie Allard et Groetembril', 'overige', 'hoge+melkzure', 'donker amber', '9,5% vol.'),
(116, 'Brunehaut 8 vieille réserve', 'Brasserie Allard et Groetembril', 'overige', 'hoge+melkzure', 'donker amber', '9,5% vol.'),
(117, 'Buffalo', 'Brouwerij van den Bossche', 'overige', 'hoge', 'zwartbruin', '5,1% vol.'),
(118, 'Bush beer', 'Brasserie Dubuisson', 'gerstewijn', 'hoge', 'amber EBC 26', '12% vol.'),
(119, 'Caeyman pils', 'Brouwerij van Roy', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(120, 'Cambrinus', 'Brouwerij Verhaeghe', 'Belgische ale', 'hoge', 'licht amber', '5,6% vol.'),
(121, 'Campbell''s christmas', 'Martinas (groep Interbrew)', 'scotch ale', 'hoge', 'donkerbruin', '8,2% vol.'),
(122, 'Campbell''s scotch', 'Martinas (groep Interbrew)', 'scotch ale', 'hoge', 'donkerbruin', '7,6% vol.'),
(123, 'Campus', 'Brouwerij Bios', 'overige', 'hoge met nof', 'amber', '8,0% vol.'),
(124, 'Cantillon druivenlambic', 'Brouwerij Cantillon', 'overige', 'spontane', 'amber', '4,9% vol.'),
(125, 'Cantillon framboise', 'Brouwerij Cantillon', 'framboise', 'spontane', 'rose', '5,4% vol.'),
(126, 'Cantillon Grand Cru', 'Brouwerij Cantillon', 'lambic', 'spontane', 'amber', '5,4% vol.'),
(127, 'Cantillon kriek', 'Brouwerij Cantillon', 'kriekenbier', 'spontane', 'rood', '5,4% vol.'),
(128, 'Cara pils', 'Brouwerij Haacht', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(129, 'Cara pils', 'Brouwerij van Roy', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(130, 'Cara pils', 'Brouwerij Martens', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(131, 'Cardor', 'Brouwerij Riva', 'overige', 'hoge', 'blond EBC 7', '8,0% vol.'),
(132, 'Carillon', 'Brasserie à Vapeur', 'overige', 'hoge met nof', 'blond', '8,0% vol.'),
(133, 'Catchpole blonde', 'Brasserie du Bocq', 'overige', 'hoge met nof', 'blond EBC 12', '7,4% vol.'),
(134, 'Catchpole brune', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin EBC 44', '8,8% vol.'),
(135, 'Caves', 'Brouwerij Verhaeghe', 'overige', 'hoge', 'licht amber', '5,1% vol.'),
(136, 'Caves Bruegel gueuze lambic', 'Brabrux (Groep Belle-Vue)', 'gueuze', 'spontane', 'amber', '5,2% vol.'),
(137, 'Caves Bruegel kriek lambic', 'Brabrux (Groep Belle-Vue)', 'kriekenbier', 'spontane', 'rood', '5,2% vol.'),
(138, 'Cervesia', 'Brasserie Dupont', 'overige', 'hoge met nof', 'licht amber', '8,5% vol.'),
(139, 'Cervoise de l''Avouerie d''Anthisnes', 'Brasserie de Silly', 'Belgische ale', 'hoge', 'amber', '5,2% vol.'),
(140, 'Cervoise du Maca', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'licht amber', '7,0% vol.'),
(141, 'Charles Quint', 'Brouwerij Haacht', 'dubbel', 'hoge', 'donkerbruin EBC 100', '6,5% vol.'),
(142, 'Christmas', 'Brouwerij Leroy', 'dubbel', 'hoge', 'donkerbruin', '8,0% vol.'),
(143, 'Christmas beer (Delhaize)', 'Brasserie du Bocq', 'scotch ale', 'hoge met nof', 'bruin EBC 44', '9,0% vol.'),
(144, 'Christmas Primus pils', 'Brouwerij Haacht', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(145, 'Class pils', 'Brouwerij van Roy', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(146, 'Contra pils', 'Brouwerij Contreras', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(147, 'Coq hardi pils', 'Brouwerij Haacht', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(148, 'Corsendonk Agnus', 'Brasserie du Bocq', 'tripel', 'hoge met nof', 'blond EBC 10', '8,10% vol.'),
(149, 'Corsendonk Agnus 75 cl.', 'Brouwerij Bios', 'overige', 'hoge met nof', 'amber', '8,0% vol.'),
(150, 'Corsendonk Agnus van het vat', 'Brouwerij de Smedt', 'overige', 'hoge', 'amber EBC 19', '6,5% vol.'),
(151, 'Corsendonk Pater', 'Brouwerij Bios', 'dubbel', 'hoge met nof', 'donkerbruin', '8,0% vol.'),
(152, 'Coy''Heimsen', 'Brouwerij van Eecke', 'dubbel', 'hoge met nof', 'donkerbruin', '6,5% vol.'),
(153, 'Cristal Alken', 'Alken-Maes (zetel Alken)', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(154, 'Cristmas van Roy', 'Brouwerij van Roy', 'bokbier', 'hoge', 'bruin EBC 90', '7,3% vol.'),
(155, 'Crom pils', 'Brouwerij Crombé', 'pilsener', 'lage', 'blond', '5,0% vol.'),
(156, 'Cupido', 'Brouwerij Bosteels', 'overige', 'hoge', 'amber EBC 32', '4,8% vol.'),
(157, 'Cuvée Bosquétia', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin', '6,7% vol.'),
(158, 'Cuvée Cervesia Tornacum', 'Brasserie Allard et Groetembril', 'overige', 'hoge+melkzure', 'donker amber', '9,5% vol.'),
(159, 'Cuvée de Blatteux', 'Brouwerij Verhaeghe', 'Belgische ale', 'hoge', 'licht amber', '5,6% vol.'),
(160, 'Cuvée de Borq - la St. Hubert', 'Brasserie Maire', 'overige', 'hoge', 'donkerbruin', '5,0% vol.'),
(161, 'Cuvée de Briqville', 'Brouwerij Bios', 'overige', 'hoge met nof', 'amber', '8,0% vol.'),
(162, 'Cuvée de Ciney blonde', 'St. Guibert (groep Interbrew)', 'overige', 'hoge', 'blond', '6,6% vol.'),
(163, 'Cuvée de Ciney brune', 'St. Guibert (groep Interbrew)', 'dubbel', 'hoge', 'bruin', '6,34% vol.'),
(164, 'Cuvée de Ciney spéciale', 'St. Guibert (groep Interbrew)', 'overige', 'hoge', 'roodbruin', '8,5% vol.'),
(165, 'Cuvée de Huy', 'Brouwerij Bios', 'gerstewijn', 'hoge met nof', 'zwartbruin', '11,0% vol.'),
(166, 'Cuvée de l''Ascension', 'Brasserie de l''Abbaye des Rocs (Brasserie Eloir-Bertiau)', 'overige', 'hoge met nof', 'donkerbruin', '9,0% vol.'),
(167, 'Cuvée de l''Ermitage', 'Union (groep Alken-Maes)', 'dubbel', 'hoge', 'bruin EBC 42', '7,0% vol.'),
(168, 'Cuvée de l''Ermitage christmas', 'Union (groep Alken-Maes)', 'dubbel', 'hoge', 'bruin EBC 42', '7,0% vol.'),
(169, 'Cuvée de l''Escapade', 'Brouwerij Bios', 'gerstewijn', 'hoge met nof', 'zwartbruin', '11,0% vol.'),
(170, 'Cuvée de la Pucelette', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'licht amber', '7,0% vol.'),
(171, 'Cuvée de la Thyria', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin', '7,4% vol.'),
(172, 'Cuvée de Namur blonde', 'Brasserie du Bocq', '?', '?', '?', 'Onbekend'),
(173, 'Cuvée de Namur blonde', 'Brouwerij L. Huyghe N.V.', 'overige', 'hoge met nof', 'blond EBC 14', '7,5% vol.'),
(174, 'Cuvée de St. Gilles blonde', 'Brouwerij Facon', 'overige', 'hoge', 'licht amber', '7,5% vol.'),
(175, 'Cuvée de St. Gilles brune', 'Brouwerij Facon', 'overige', 'hoge', 'roodbruin EBC 10', '7,5% vol.'),
(176, 'Cuvée des Blatteux', 'Brouwerij Verhaeghe', 'Belgische ale', 'hoge', 'licht amber', '5,6% vol.'),
(177, 'Cuvée des Forges', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'amber', '8% vol.'),
(178, 'Cuvée des Hauts Voués', 'Brasserie de Silly', 'dubbel', 'hoge', 'lichtbruin', '8,0% vol.'),
(179, 'Cuvée des moissons blonde', 'Brasserie à Vapeur', 'overige', 'hoge met nof', 'bruin', '8,0% vol.'),
(180, 'Cuvée des moissons rousse', 'Brasserie à Vapeur', 'overige', 'hoge met nof', 'blond', '8,0% vol.'),
(181, 'Cuvée du Brochon', 'Brasserie de l''Abbaye des Rocs (Brasserie Eloir-Bertiau)', 'overige', 'hoge', 'bruinrood', '6,8% vol.'),
(182, 'Cuvée du P''tit Lu', 'Brasserie du Bocq', 'saison', 'hoge met nof', 'amber EBC 23', '6,1% vol.'),
(183, 'Cuvée du Tchop', 'Brasserie de Silly', 'dubbel', 'hoge', 'lichtbruin', '8,0% vol.'),
(184, 'Cuvée Gerpinoise', 'Brasserie de Silly', 'dubbel', 'hoge', 'lichtbruin', '8,0% vol.'),
(185, 'Cuvée Li Crochon', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin EBC 44', '8,8% vol.'),
(186, 'Cuvée Piconrue', 'Brasserie d''Achouffe', 'overige', 'hoge met nof', 'donkerbruin', '8,0% vol.'),
(187, 'Cuvée spéciale de Chèvremont', 'Brasserie du Bocq', 'overige', 'hoge met nof', 'blond EBC 12', '7,4% vol.'),
(188, 'Cuvée St. Antoine', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin EBC 44', '8,8% vol.'),
(189, 'Cuvée St. Berthuin', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'licht amber', '7,0% vol.'),
(190, 'Cuvée St.Amand', 'Bavik - De Brabandere', 'tripel', 'hoge', 'licht amber EBC 16', '7,5% vol.'),
(191, 'Da Vinci', 'Brasserie de Silly', 'dubbel', 'hoge', 'lichtbruin', '8,0% vol.'),
(192, 'Daiselnaere', 'Brouwerij De Gouden Boom', 'dubbel', 'hoge met nof', 'bruin', '6,5% vol.'),
(193, 'De Brouwers van de Dijle', 'Lamot (groep Interbrew)', 'pilsener', 'lage', 'blond', '5,25% vol.'),
(194, 'De Koninck', 'Brouwerij De Koninck', 'Belgische ale', 'hoge', 'amber EBC 23', '5,0% vol.'),
(195, 'De Koninck gueuze', 'Gueuzestekerij De Koninck', 'gueuze', 'spontane nof', 'amber', '5,0% vol.'),
(196, 'De Koninck kriek', 'Gueuzestekerij De Koninck', 'kriekenbier', 'spontane', 'rood', '5,2% vol.'),
(197, 'De Neve frambozen', 'De Neve (groep Belle-Vue)', 'framboise', 'spontane', 'rood-amber', '5,2% vol.'),
(198, 'De Neve gueuze gefilterd', 'De Neve (groep Belle-Vue)', 'gueuze', 'spontane', 'amber', '5,2% vol.'),
(199, 'De Neve gueuze met hergisting', 'De Neve (groep Belle-Vue)', 'gueuze', 'spontane nof', 'amber', '5,2% vol.'),
(200, 'De Neve kriek lambic', 'De Neve (groep Belle-Vue)', 'kriekenbier', 'spontane', 'rood', '5,2% vol.'),
(201, 'De Pompeschitter', 'Brouwerij Leroy', 'overige', 'hoge', 'bruin', '7,0% vol.'),
(202, 'De Ryck christmas pale ale', 'Brouwerij de Ryck', 'ale', 'hoge', 'amber', '5,4% vol.'),
(203, 'De Troch banane-lambic', 'Brouwerij de Troch', 'overige', 'spontane', 'amber', '5,0% vol.'),
(204, 'De Troch framboise', 'Brouwerij de Troch', 'overige', 'spontane', 'lichtrood', '3,0% vol.'),
(205, 'De Troch gueuze', 'Brouwerij de Troch', 'gueuze', 'spontane nof', 'amber', '5,0% vol.'),
(206, 'De Troch kriek', 'Brouwerij de Troch', 'kriekenbier', 'spontane nof', 'rood', '5,5% vol.'),
(207, 'De Troch mirabelle', 'Brouwerij de Troch', 'overige', 'spontane', 'amber', '3,0% vol.'),
(208, 'De Troch pêche', 'Brouwerij de Troch', 'overige', 'spontane', 'amber', '3,0% vol.'),
(209, 'De Verboden Vrucht', 'Brouwerij De Kluis (groep Interbrew)', 'overige', '?', '?', 'Onbekend'),
(210, 'Deca pils', 'Brouwerij Isebaert', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(211, 'Deconinck pils', 'Brouwerij Riva', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(212, 'Den Bleeken Moriaan', 'Brouwerij van Eecke', 'overige', 'hoge met nof', 'blond', '10,0% vol.'),
(213, 'Den Bruynen Moriaen', 'Brouwerij van Eecke', 'overige', 'hoge met nof', 'donkerbruin', '9,0% vol.'),
(214, 'Dentergems witbier - Riva blanche', 'Brouwerij Riva', 'witbier', 'hoge met nof', 'blond EBC 5', '5,0% vol.'),
(215, 'Derby pils', 'Brouwerij Haacht', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(216, 'Dikke', 'Brouwerij de Smet', 'overige', 'lage', 'bruin EBC 50', '7,4% vol.'),
(217, 'Dikke Mathile', 'Brouwerij Strubbe', 'ale', 'hoge', 'amber', '6,0% vol.'),
(218, 'Dilirium tremens', 'Brouwerij L. Huyghe N.V.', 'overige', 'hoge met nof', 'licht amber', '9,5% vol.'),
(219, 'Dobbel Palm', 'Brouwerij Palm', 'Belgische ale', 'hoge', 'amber EBC 24', '5,5% vol.'),
(220, 'Dobbelen bruinen', 'Brouwerij Roman', 'Vlaamse bruine', 'hoge met nof', 'bruin EBC 70', '8,0% vol.'),
(221, 'Dobbelken', 'Brouwerij Strubbe', 'Vlaamse bruine', 'hoge+melkzure', 'roodbruin', '5,0% vol.'),
(222, 'Domein donker', 'Brouwerij Bios', 'dubbel', 'hoge met nof', 'donkerbruin', '8,0% vol.'),
(223, 'Domein licht', 'Brouwerij Bios', 'overige', 'hoge met nof', 'amber', '8,0% vol.'),
(224, 'Domus', 'Huisbrouwerij Domus', 'overige', 'lage', 'amber', '4,0% vol.'),
(225, 'Dorée', 'Brasserie Lefèbvre', 'saison', 'hoge met nof', 'blond', '5,5% vol.'),
(226, 'Dorp pils', 'Brouwerij van Roy', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(227, 'Double abbaye de flandres', 'Brouwerij Riva', 'dubbel', 'hoge', 'bruin EBC 50', '6,2% vol.'),
(228, 'Double Enghien Spéciale', 'Brasserie de Silly', 'dubbel', 'hoge', 'lichtbruin', '8,0% vol.'),
(229, 'Double spéciale bière d''abbaye Enghien', 'Brasserie de Silly', 'dubbel', 'hoge', 'lichtbruin', '8,0% vol.'),
(230, 'Doublette d''Enghien', 'Brasserie de Silly', 'saison', 'hoge', 'amber', '5,8% vol.'),
(231, 'Drie Fonteinen framboos', 'Gueuzestekerij Drie Fonteinen', 'framboise', 'spontane', 'donker amber', '6,0% vol.'),
(232, 'Drie Fonteinen gueuze', 'Gueuzestekerij Drie Fonteinen', 'gueuze', 'spontane+nof', 'amber', '5,5% vol.'),
(233, 'Drongens plezierke', 'Brouwerij Slagmuylder', 'dubbel', 'hoge met nof', 'donkerbruin', '7,8% vol.'),
(234, 'Dubbel Domus honingbier', 'Huisbrouwerij Domus', 'overige', 'lage', 'amber', '6,0% vol.'),
(235, 'Duivels bier', 'Brouwerij Vander Linden', 'overige', 'spontane+hoge', 'donker amber', '5,5% vol.'),
(236, 'Duvel pils', 'Brouwerij Moortgat', 'pilsener', 'lage', 'blond EBC 6', '5,1% vol.'),
(237, 'E noed''n pannenoare', 'Brasserie Dupont', 'overige', 'hoge met nof', 'licht amber', '8,5% vol.'),
(238, 'E.S.P. extra strong pils', 'Brouwerij van Roy', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(239, 'Echte kriek', 'Brouwerij Verhaeghe', 'kriekenbier', 'hoge', 'dieprood', '5,8% vol.'),
(240, 'Eksaardse Blauwbuik', 'Brouwerij Bios', 'overige', 'hoge met nof', 'amber', '8,0% vol.'),
(241, 'El Vert Doudou', 'Brasserie à Vapeur', 'overige', 'hoge met nof', 'bruin', '8,0% vol.'),
(242, 'Elckerlyc', 'Brouwerij Callewaert', 'pale ale', 'hoge', 'amber', '6,5% vol.'),
(243, 'Engeltjesbier', 'Brouwerij ''t Steedje', 'overige', 'hoge met nof', 'amber', '10,0% vol.'),
(244, 'Eupener export', 'Eupener Bierbrauerei', 'pilsener', 'lage', 'blond', '4,3% vol.'),
(245, 'Eupener kapuziner klosterbier', 'Eupener Bierbrauerei', 'overige', 'lage', 'donkerbruin', '5,0% vol.'),
(246, 'Eupener pils', 'Eupener Bierbrauerei', 'pilsener', 'lage', 'blond', '4,6% vol.'),
(247, 'Ever natuurbier', 'Brouwerij Neyt', 'pilsener', 'lage', 'blond EBC 15', '5,5% vol.'),
(248, 'Extra pilsener', 'Brouwerij Moortgat', 'pilsener', 'lage', 'blond EBC 6', '5.0% vol.'),
(249, 'Extra stout', 'Brouwerij Callewaert', 'stout', 'lage', 'donkerbruin', '5,0% vol.'),
(250, 'Extra stout', 'Brasserie Lefèbvre', 'stout', 'hoge', 'zwartbruin', '6,5% vol.'),
(251, 'Ezel', 'Brouwerij Verhaeghe', 'overige', 'hoge', 'licht amber', '6,0% vol.'),
(252, 'Facon export', 'Brouwerij Facon', 'pilsener', 'lage', 'blond', '4,0% vol.'),
(253, 'Facon extra stout', 'Brouwerij Facon', 'stout', 'hoge', 'zwartbruin', '7,5% vol.'),
(254, 'Facon ouden bruin', 'Brouwerij Facon', 'Vlaamse bruine', 'hoge+melkzure', 'donkerbruin', '4,9% vol.'),
(255, 'Facon pils', 'Brouwerij Facon', 'pilsener', 'lage', 'blond', '4,9% vol.'),
(256, 'Facon scotch-christmas', 'Brouwerij Facon', 'scotch ale', 'hoge', 'donker amber', '7,5% vol.'),
(257, 'Fakir', 'Brasserie la Binchoise', 'overige', 'hoge met nof', 'blond', '6,2% vol.'),
(258, 'Fana Blonde', 'Brasserie du Bocq', 'tripel', 'hoge met nof', 'blond EBC 10', '8,10% vol.'),
(259, 'Fana brune', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin', '7,4% vol.'),
(260, 'Fancy', 'Bavik - De Brabandere', 'stout', 'lage', 'zwartbruin', '4,9% vol.'),
(261, 'Fantôme', 'Brasserie Fantôme', 'overige', 'hoge met nof', 'bruin', '8,0% vol.'),
(262, 'Faro extra', 'Brouwerij van Roy', 'faro', 'spontane', 'bruin EBC 85', '4,9% vol.'),
(263, 'Faro Lambic Lindemans', 'Brouwerij Lindemans', 'faro', 'spontane', 'amber', '4,2% vol.'),
(264, 'Faro Pertotale', 'Brouwerij Frank Boon N.V.', 'faro', 'spontane+hoge', 'amber', '6,0% vol.'),
(265, 'Faro Vieux Foudre', 'Brouwerij Vander Linden', 'faro', 'spontane', 'amber', '5,5% vol.'),
(266, 'Fausse Qau', 'Brasserie du Bocq', 'overige', 'hoge met nof', 'blond EBC 12', '7,4% vol.'),
(267, 'Felix kriek oud bruin', 'Brouwerij Clarysse', 'kriekenbier', 'hoge', 'roodbruin', '5,5% vol.'),
(268, 'Felix kriekbier', 'Brouwerij Clarysse', 'kriekenbier', 'hoge', 'roodbruin', '5,5% vol.'),
(269, 'Felix Oudenaards kriekbier', 'Brouwerij Clarysse', 'kriekenbier', 'hoge', 'roodbruin', '6,0% vol.'),
(270, 'Felix Oudenaards oud bruin', 'Brouwerij Clarysse', 'Vlaamse bruine', 'hoge', 'bruin', '5,5% vol.'),
(271, 'Felix speciaal Oudenaards', 'Brouwerij Clarysse', 'Vlaamse bruine', 'hoge', 'bruin', '4,8% vol.'),
(272, 'Flandrien', 'Brouwerij Louwaege', 'Belgische ale', 'hoge', 'blond EBC 11', '5,0% vol.'),
(273, 'Floreffe blond 7', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'licht amber', '7,0% vol.'),
(274, 'Floreffe double', 'Brasserie Lefèbvre', 'dubbel', 'hoge met nof', 'bruin', '7,0% vol.'),
(275, 'Floreffe la Meilleure', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'bruinrood', '9,0% vol.'),
(276, 'Floreffe triple', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'amber', '8% vol.'),
(277, 'Fortuyn', 'Brasserie de Silly', 'saison', 'hoge', 'amber', '5,8% vol.'),
(278, 'Foudroyante pêche', 'Brouwerij Lindemans', 'perzikbier', 'spontane', 'blond', '3,6% vol.'),
(279, 'Framboise Boon', 'Brouwerij Frank Boon N.V.', 'framboise', 'spontane nof', 'rose', '6,2% vol.'),
(280, 'Frambozenbier', 'Brouwerij Vander Linden', 'framboise', 'hoge met nof', 'donker amber', '7,0% vol.'),
(281, 'Freutche', 'Brasserie Lefèbvre', 'saison', 'hoge', 'amber', '5,0% vol.'),
(282, 'Frissing christmas', 'Brouwerij van Roy', 'bokbier', 'hoge', 'bruin EBC 90', '7,3% vol.'),
(283, 'Frissing pils', 'Brouwerij van Roy', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(284, 'Gala pils', 'Brouwerij Haacht', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(285, 'Gapersbier', 'Brouwerij Verhaeghe', 'overige', 'hoge', 'licht amber', '6,0% vol.'),
(286, 'Géant Altas 8', 'Brasserie Allard et Groetembril', 'overige', 'hoge+melkzure', 'donker amber', '9,5% vol.'),
(287, 'Géant Atlas 9', 'Brasserie Allard et Groetembril', 'gerstewijn', 'hoge met nof', 'bruin', '10,5% vol.'),
(288, 'Gildenbier', 'Brouwerij Haacht', 'overige', 'hoge', 'donkerbruin EBC 100', '6,8% vol.'),
(289, 'Ginder ale', 'Martinas (groep Interbrew)', 'Belgische ale', 'hoge', 'amber', '5,1% vol.'),
(290, 'Girardin gueuze 1882', 'Brouwerij Girardin', 'gueuze', 'spontane', 'amber', '5,0% vol.'),
(291, 'Girardin kriek 1882', 'Brouwerij Girardin', 'kriekenbier', 'spontane', 'rood', '5,2% vol.'),
(292, 'Gluck pils', 'Brouwerij van Roy', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(293, 'Godefroy', 'Brouwerij Moortgat', 'overige', 'hoge met nof', 'amber EBC 30', '5,6% vol.'),
(294, 'Gold pils', 'Brouwerij van Roy', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(295, 'Golden Girl pils', 'Brouwerij Isebaert', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(296, 'Golden hop pils', 'Bavik - De Brabandere', '?', '?', '?', 'Onbekend'),
(297, 'Golden Kenia', 'Brouwerij L. Huyghe N.V.', 'pilsener', 'lage', 'blond EBC 8', '5,1% vol.'),
(298, 'Golding Campina', 'Brouwerij Campina', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(299, 'Gouden Carolus', 'Brouwerij Het Anker', 'overige', 'hoge met nof', 'bruin', '7,0% vol.'),
(300, 'Grimbergen dubbel', 'Union (groep Alken-Maes)', 'dubbel', 'hoge', 'donkerbruin EBC 70', '6,0% vol.'),
(301, 'Grimbergen optimo bruno', 'Union (groep Alken-Maes)', 'gerstewijn', 'hoge', 'lichtbruin EBC 35', '10,0% vol.'),
(302, 'Grimbergen tripel', 'Union (groep Alken-Maes)', 'tripel', 'hoge', 'blond EBC 15', '8,0% vol.'),
(303, 'Grisette bière du cayoteu', 'Brasserie de Silly', 'Belgische ale', 'hoge', 'amber', '5,2% vol.'),
(304, 'Gueuze F.Boon', 'Brouwerij Frank Boon N.V.', 'gueuze', 'spontane nof', 'amber', '6,0% vol.'),
(305, 'Gueuze F.Boon "Mariage parfait"', 'Brouwerij Frank Boon N.V.', 'gueuze', 'spontane nof', 'amber', '6,0% vol.'),
(306, 'Gueuze framboisée des Ardennes', 'Brouwerij De Keersmaeker (groep Alken-Maes)', 'framboise', 'spontane', 'rood-amber', '4,0% vol.'),
(307, 'Gueuze lambic Eylenbosch', 'Brouwerij Eyelenbosch (groep Alken-Maes)', 'gueuze', 'spontane', 'amber', '5,0% vol.'),
(308, 'Gueuze Oud Beersel', 'Vandervelden', 'gueuze', 'spontane', 'amber', '6,0% vol.'),
(309, 'Gueuze Vieux Foudre', 'Brouwerij Vander Linden', 'gueuze', 'spontane nof', 'amber', '5,5% vol.'),
(310, 'Gulden Draak', 'Brouwerij Bios', 'gerstewijn', 'hoge met nof', 'zwartbruin', '11,0% vol.'),
(311, 'Haacht export', 'Brouwerij Haacht', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(312, 'Haecht tarwebier', 'Brouwerij Haacht', 'witbier', 'hoge met nof', 'blond', '5,0% vol.'),
(313, 'Hanssens gueuze', 'Gueuzestekerij Hanssens', 'gueuze', 'spontane', 'amber', '5,5% vol.'),
(314, 'Hanssens kriek', 'Gueuzestekerij Hanssens', 'kriekenbier', 'spontane', 'rood', '6,0% vol.'),
(315, 'Hapkin', 'Brouwerij Louwaege', 'overige', 'hoge met nof', 'blond EBC 9', '8,5% vol.'),
(316, 'Hellestraatse bruine', 'Brouwerij de Smedt', 'Belgische ale', 'hoge', 'amber EBC 20', '5,0% vol.'),
(317, 'Herbakkersbier', 'Brouwerij de Block', 'overige', 'hoge', 'donker amber', '6,4% vol.'),
(318, 'Hercule Poirot', 'Brasserie Allard et Groetembril', 'gerstewijn', 'hoge met nof', 'bruin', '10,5% vol.'),
(319, 'Hert ale', 'Brouwerij De Keersmaeker (groep Alken-Maes)', 'Belgische ale', 'hoge', 'licht amber', '5,0% vol.'),
(320, 'Hertog Jan Pilsener', 'Artois (groep Interbrew)', 'pilsener', 'lage', 'blond', '5,1% vol.'),
(321, 'Het Kapittel abt', 'Brouwerij van Eecke', 'overige', 'hoge met nof', 'blond', '10,0% vol.'),
(322, 'Het Kapittel dubbel', 'Brouwerij van Eecke', 'dubbel', 'hoge met nof', 'donkerbruin', '7,5% vol.'),
(323, 'Het Kapittel pater', 'Brouwerij van Eecke', 'dubbel', 'hoge met nof', 'donkerbruin', '6,5% vol.'),
(324, 'Het Kapittel prior', 'Brouwerij van Eecke', 'overige', 'hoge met nof', 'donkerbruin', '9,0% vol.'),
(325, 'Hoegaarden grand cru', 'Brouwerij De Kluis (groep Interbrew)', 'tripel', 'hoge met nof', 'blond EBC 11', '8,7% vol.'),
(326, 'Holtland lager bier', 'Brouwerij Haacht', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(327, 'Horse ale', 'Lamot (groep Interbrew)', 'Belgische ale', 'hoge', 'amber', '4,9% vol.'),
(328, 'Hotteuse grand cru', 'Brouwerij Roman', 'tripel', 'hoge met nof', 'licht amber EBC 23', '7,1% vol.'),
(329, 'Houten kop', 'Brouwerij Strubbe', 'overige', 'hoge met nof', 'amber', '6,5% vol.'),
(330, 'Huyghe export', 'Brouwerij L. Huyghe N.V.', 'pilsener', 'lage', 'blond EBC 8', '4,5% vol.'),
(331, 'Ichtegems oud bruin', 'Brouwerij Strubbe', 'Vlaamse bruine', 'hoge+melkzure', 'roodbruin', '5,0% vol.'),
(332, 'Iguanodon', 'Brasserie la Binchoise', 'overige', 'hoge met nof', 'blond', '6,2% vol.'),
(333, 'Interpils', 'Brouwerij Riva', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(334, 'Jack-Op', 'Brabrux (Groep Belle-Vue)', 'overige', 'hoge+spontane', 'amber', '5,0% vol.'),
(335, 'Jacobins frambozen', 'Brouwerij Bockor', 'framboise', 'hoge+melkzure', 'amber', '5,7% vol.'),
(336, 'Jacobins gueuze lambic', 'Brouwerij Bockor', 'gueuze', 'hoge+melkzure', 'amber EBC 24', '5,7% vol.'),
(337, 'Jacobins kriek lambic', 'Brouwerij Bockor', 'kriekenbier', 'hoge+melkzure', 'roodbruin', '5,7% vol.'),
(338, 'Jan Buuc', 'Brouwerij Leroy', 'overige', 'hoge', 'bruin', '7,0% vol.'),
(339, 'Jean de Nivilles', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin', '7,4% vol.'),
(340, 'Jeunesse de St-Remy', 'Brouwerij Bios', 'tripel', 'hoge met nof', 'blond', '9,0% vol.'),
(341, 'Jobarde', 'Brasserie à Vapeur', 'overige', 'hoge met nof', 'bruin', '8,0% vol.'),
(342, 'Jot-pils', 'Brouwerij Riva', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(343, 'Judas', 'Brouwerij van Zulte', 'overige', 'hoge met nof', 'blond EBC 9', '8,5% vol.'),
(344, 'Julius', 'Brouwerij De Kluis (groep Interbrew)', 'overige', 'hoge met nof', 'blond EBC 13', '8.7% vol.'),
(345, 'Jupiler', 'Kruger (groep Interbrew)', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(346, 'Kanterbräu', 'Alken-Maes (zetel Alken)', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(347, 'Kapucienestraetebier', 'Brouwerij Verhaeghe', 'overige', 'hoge', 'licht amber', '5,1% vol.'),
(348, 'Karlsquell', 'Brouwerij Martens', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(349, 'Kastaar', 'Brouwerij de Block', 'overige', 'hoge', 'donker amber', '6,4% vol.'),
(350, 'Kerelsbier donker', 'Brouwerij Leroy', 'overige', 'hoge', 'bruin', '7,0% vol.'),
(351, 'Kerelsbier licht', 'Brouwerij Leroy', 'superpils', 'lage', 'blond', '6,5% vol.'),
(352, 'Kerstbier', 'Brouwerij van den Bossche', 'overige', 'hoge', 'bruin', '5,2% vol.'),
(353, 'Kluyserbier', 'Brouwerij Sterkens', 'ale', 'hoge', 'donker amber', '6,5% vol.'),
(354, 'Kob pilsener', 'Brouwerij De Keersmaeker (groep Alken-Maes)', 'pilsener', 'lage', 'blond', '5,0% vol.'),
(355, 'kriek', 'Brouwerij van Roy', 'kriekenbier', 'spontane', 'rood EBC 34', '4,8% vol.'),
(356, 'Kriek F.Boon', 'Brouwerij Frank Boon N.V.', 'kriekenbier', 'spontane nof', 'rood', '6,5% vol.'),
(357, 'Kriek F.Boon "mariage parfait"', 'Brouwerij Frank Boon N.V.', 'kriekenbier', 'spontane nof', 'rood', '6,5% vol.'),
(358, 'Kriek lambic Eylenbosch', 'Brouwerij Eyelenbosch (groep Alken-Maes)', 'kriekenbier', 'spontane', 'rood', '5,2% vol.'),
(359, 'Kriek Oud Beersel', 'Brouwerij Museum Oud Beersel', 'kriekenbier', 'spontane', 'rood', '7,0% vol.'),
(360, 'Kriek Vieux Foudre', 'Brouwerij Vander Linden', 'kriekenbier', 'spontane nof', 'rood', '5,5% vol.'),
(361, 'Kriek-lambic Drie Fonteinen', 'Gueuzestekerij Drie Fonteinen', 'kriekenbier', 'spontane', 'rood', '6,0% vol.'),
(362, 'Kriekenbier', 'Brouwerij St. Jozef', 'kriekenbier', 'lage', 'roodbruin EBC 20', '4,6% vol.'),
(363, 'Kronenbourg', 'Alken-Maes (zetel Alken)', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(364, 'Krüger export beer', 'Kruger (groep Interbrew)', 'pilsener', 'lage', 'blond', '4,7% vol.'),
(365, 'Krüger pils', 'Kruger (groep Interbrew)', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(366, 'L''Anvinoise', 'Brasserie à Vapeur', 'overige', 'hoge met nof', 'blond', '8,0% vol.'),
(367, 'L''Arsouye blonde', 'Brasserie du Bocq', 'overige', 'hoge met nof', 'blond EBC 12', '7,4% vol.'),
(368, 'L''Arsouye brune', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin', '7,4% vol.'),
(369, 'L''Eblouissante', 'Brasserie d''Achouffe', 'overige', 'hoge met nof', 'donkerbruin', '8,0% vol.'),
(370, 'L''Eveil Wallon', 'Brasserie Dupont', 'overige', 'hoge met nof', 'licht amber', '8,5% vol.'),
(371, 'L''Gayette', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin', '7,4% vol.'),
(372, 'L''Vapeur en folie', 'Brasserie à Vapeur', 'overige', 'hoge met nof', 'bruin', '8,0% vol.'),
(373, 'L''Vapeur rousse', 'Brasserie à Vapeur', 'overige', 'hoge met nof', 'blond', '8,0% vol.'),
(374, 'La Bergeotte', 'Brasserie du Bocq', 'saison', 'hoge met nof', 'amber EBC 23', '6,1% vol.'),
(375, 'La Bergeotte', 'Brasserie du Bocq', 'saison', 'hoge met nof', 'amber EBC 23', '6,1% vol.'),
(376, 'La bière du Grand monarque', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin', '6,7% vol.'),
(377, 'La Boum 6', 'Brasserie Allard et Groetembril', 'saison', 'hoge met nof', 'amber', '7,0% vol.'),
(378, 'La Boum 8', 'Brasserie Allard et Groetembril', 'overige', 'hoge+melkzure', 'donker amber', '9,5% vol.'),
(379, 'La Boussutoise - Biére des fagnes', 'Brasserie du Bocq', '?', '?', '?', 'Onbekend'),
(380, 'La Buxus', 'Brasserie la Binchoise', 'overige', 'hoge met nof', 'bruin', '8,3% vol.'),
(381, 'La Cervoise de St. Gery', 'Brasserie Dupont', 'overige', 'hoge met nof', 'licht amber', '8,5% vol.'),
(382, 'La Cervoise des Fracs-Gaulois', 'Brasserie Dupont', 'overige', 'hoge met nof', 'licht amber', '8,5% vol.'),
(383, 'La Communiale', 'Brasserie d''Achouffe', 'overige', 'hoge met nof', 'donkerbruin', '8,0% vol.'),
(384, 'La Condrusienne', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'licht amber', '7,0% vol.'),
(385, 'La Crupettoise', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin', '7,4% vol.'),
(386, 'La Cuvée des Purleux', 'Brasserie Dupont', 'overige', 'hoge met nof', 'licht amber', '8,5% vol.'),
(387, 'La Diva', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'amber', '8% vol.'),
(388, 'La Druide', 'Brasserie Allard et Groetembril', 'gerstewijn', 'hoge met nof', 'bruin', '10,5% vol.'),
(389, 'La Druide 10', 'Brasserie Allard et Groetembril', 'gerstewijn', 'hoge met nof', 'bruin', '10,5% vol.'),
(390, 'La Durboyse', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'licht amber', '7,0% vol.'),
(391, 'La Fleurie de Wanze', 'Brasserie d''Achouffe', 'overige', 'hoge met nof', 'donkerbruin', '8,0% vol.'),
(392, 'La Gauloise 8°', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin EBC 44', '8,8% vol.'),
(393, 'La Gaumaise', 'Brasserie Maire', 'overige', 'hoge', 'amber', '5,0% vol.'),
(394, 'La Gaumaise brune', 'Brasserie Maire', 'overige', 'hoge', 'donkerbruin', '5,0% vol.'),
(395, 'La Geldonia', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin', '7,4% vol.'),
(396, 'La Glorieuse', 'Brasserie d''Achouffe', 'overige', 'hoge met nof', 'blond', '8,0% vol.'),
(397, 'La Hamaide', 'Brasserie Voisin', 'saison', 'hoge', 'licht amber', '5,5% vol.'),
(398, 'La Houlette', 'Brasserie du Bocq', 'saison', 'hoge met nof', 'amber EBC 23', '6,1% vol.'),
(399, 'La Joyeuse (blonde)', 'Brasserie Dupont', 'overige', 'hoge met nof', 'licht amber', '8,5% vol.'),
(400, 'La Joyeuse (brune)', 'Brasserie Dupont', 'overige', 'hoge met nof', 'donker amber', '8,5% vol.'),
(401, 'La Laekenoise', 'Brasserie du Bocq', 'overige', 'hoge met nof', 'blond EBC 12', '7,4% vol.'),
(402, 'La Liègeoise blonde', 'Brouwerij Riva', 'overige', 'hoge', 'blond EBC 7', '8,0% vol.'),
(403, 'La Liègeoise brune', 'Brouwerij Riva', 'dubbel', 'hoge met nof', 'bruin EBC 45', '8,0% vol.'),
(404, 'La Louvoise', 'Brasserie du Bocq', 'overige', 'hoge met nof', 'blond EBC 12', '7,4% vol.'),
(405, 'La Malmédy blonde', 'Brasserie d''Achouffe', 'overige', 'hoge met nof', 'blond', '8,0% vol.'),
(406, 'La Malmédy brune', 'Brasserie d''Achouffe', 'overige', 'hoge met nof', 'donkerbruin', '8,0% vol.'),
(407, 'La Marquise blonde', 'Brouwerij Riva', 'overige', 'hoge', 'blond EBC 7', '8,0% vol.'),
(408, 'La Marquise brune', 'Brouwerij Riva', 'tripel', 'hoge', 'amber EBC 23', '8,0% vol.'),
(409, 'La Moinette des Sorcières de Warquignies', 'Brasserie Dupont', 'overige', 'hoge met nof', 'licht amber', '8,5% vol.'),
(410, 'La Moneuse', 'Brasserie de Blaugies', 'overige', 'hoge met nof', 'donker amber', '±6,0% vol.'),
(411, 'La Moneuse Spéciale Noël', 'Brasserie de Blaugies', 'overige', 'hoge met nof', 'bruin', '±6,5% vol.'),
(412, 'La Montagnarde', 'Brasserie de l''Abbaye des Rocs (Brasserie Eloir-Bertiau)', 'overige', 'hoge met nof', 'bruin', '8,0% vol.'),
(413, 'La Naiade - Cuvée du Carnaval Tournai', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'amber', '8% vol.'),
(414, 'La Neuvilloise', 'Brasserie d''Achouffe', 'overige', 'hoge met nof', 'donkerbruin', '8,0% vol.'),
(415, 'La Petite follie', 'Brasserie de Silly', 'overige', 'hoge met nof', 'blond', '6,2% vol.'),
(416, 'La Poiluchette blonde', 'Brouwerij L. Huyghe N.V.', 'overige', 'hoge met nof', 'amber', '7,5% vol.'),
(417, 'La Poiluchette blonde', 'Brouwerij L. Huyghe N.V.', 'overige', 'hoge met nof', 'blond EBC 14', '7,5% vol.'),
(418, 'La Poiluchette brune', 'Brouwerij L. Huyghe N.V.', 'overige', 'hoge met nof', 'bruin', '7,5% vol.'),
(419, 'La Poiluchette brune', 'Brouwerij L. Huyghe N.V.', 'dubbel', 'hoge met nof', 'bruin EBC 75', '7,5% vol.'),
(420, 'La Seigneurie', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'licht amber', '7,0% vol.'),
(421, 'La Vieille bon secours', 'Brouwerij Riva', 'tripel', 'hoge', 'amber EBC 23', '8,0% vol.'),
(422, 'La Vieille Salme', 'Brasserie d''Achouffe', 'overige', 'hoge met nof', 'oranjegeel', '8,0% vol.'),
(423, 'La Vieillotte du Hurlevent', 'Brasserie Dupont', 'overige', 'hoge met nof', 'licht amber', '8,5% vol.'),
(424, 'Lamoral Degmont', 'Brouwerij van den Bossche', 'tripel', 'hoge met nof', 'blond', '8,0% vol.'),
(425, 'Lamot export', 'Lamot (groep Interbrew)', 'pilsener', 'lage', 'blond', '5,25% vol.'),
(426, 'Lamot pilsor', 'Lamot (groep Interbrew)', 'pilsener', 'lage', 'blond', '5,25% vol.'),
(427, 'Le Cougnet', 'Brasserie d''Achouffe', 'overige', 'hoge met nof', 'donkerbruin', '8,0% vol.'),
(428, 'Le Roy christmas', 'Brouwerij Leroy', 'overige', 'hoge', 'lichtbruin', '8,0% vol.'),
(429, 'Le Vaudrée', 'Brouwerij Bios', 'gerstewijn', 'hoge met nof', 'zwartbruin', '11,0% vol.'),
(430, 'Leffe bière russe', 'St. Guibert (groep Interbrew)', 'overige', 'hoge', 'bruin', 'Onbekend'),
(431, 'Leffe blonde', 'St. Guibert (groep Interbrew)', 'overige', 'hoge', 'blond', '6,6% vol.'),
(432, 'Leffe brune', 'St. Guibert (groep Interbrew)', 'dubbel', 'hoge', 'bruin', '6,34% vol.'),
(433, 'Leffe radieuse', 'St. Guibert (groep Interbrew)', 'overige', 'hoge', 'roodbruin', '8,5% vol.'),
(434, 'Leffe triple', 'Brasserie du Bocq', 'tripel', 'hoge met nof', 'blond EBC 10', '8,10% vol.'),
(435, 'Leffe vieille cuvée 8', 'St. Guibert (groep Interbrew)', 'overige', 'hoge', 'amber', '8,4% vol.'),
(436, 'Lekkerbek', 'Brouwerij Riva', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(437, 'Li Pir''êye di Licint 6.5', 'Brasserie la Binchoise', 'overige', 'hoge met nof', 'blond', '6,2% vol.'),
(438, 'Lichtaartse Kwezel', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'licht amber', '7,0% vol.'),
(439, 'Liefmans', 'Brouwerij Liefmans (groep Riva)', 'Vlaamse bruine', 'hoge', 'donkerbruin', '5,0% vol.'),
(440, 'Liefmans frambozenbier', 'Brouwerij Liefmans (groep Riva)', 'framboise', '?', '?', 'Onbekend'),
(441, 'Liefmans Goudenband', 'Brouwerij Liefmans (groep Riva)', 'Vlaamse bruine', '?', '?', 'Onbekend'),
(442, 'Liefmans kriekbier', 'Brouwerij Liefmans (groep Riva)', 'kriekenbier', 'hoge', 'donkerbruin', '7,1% vol.'),
(443, 'Liezelse witte', 'Brouwerij Vieille Villers', 'witbier', 'lage', 'blond', '5,3% vol.'),
(444, 'Lilliput - elisir degli gnomi', 'Brasserie d''Achouffe', 'overige', 'hoge met nof', 'oranjegeel', '8,0% vol.'),
(445, 'Lindemans cassis', 'Brouwerij Lindemans', 'cassisbier', 'spontane', 'bruin', '3,9% vol.'),
(446, 'Lindemans framboise', 'Brouwerij Lindemans', 'framboise', 'spontane', 'roodbruin', '3,6% vol.'),
(447, 'Lindemans gueuze gefilterd', 'Brouwerij Lindemans', 'gueuze', 'spontane', 'amber', '5,0% vol.'),
(448, 'Lindemans gueuze ongefilterd', 'Brouwerij Lindemans', 'gueuze', 'spontane nof', 'amber', '5,5% vol.'),
(449, 'Lindemans kriek', 'Brouwerij Lindemans', 'kriekenbier', 'spontane', 'rood', '3,9% vol.'),
(450, 'Livinus blonde', 'Brouwerij van Eecke', 'overige', 'hoge met nof', 'blond', '10,0% vol.'),
(451, 'Livinus brune', 'Brouwerij van Eecke', 'overige', 'hoge met nof', 'donkerbruin', '9,0% vol.'),
(452, 'Loburg', 'Artois (groep Interbrew)', 'superpils', 'lage', 'blond', '5,8% vol.'),
(453, 'Loteling (donker)', 'Brouwerij Vieille Villers', 'dubbel', 'hoge', 'donkerbruin', '6,3% vol.'),
(454, 'Loteling licht', 'Brouwerij Vieille Villers', 'overige', 'hoge', 'blond', '6,9% vol.'),
(455, 'Louwaege export', 'Brouwerij Louwaege', 'pilsener', 'lage', 'blond EBC 7', '4,5% vol.'),
(456, 'Louwaege stout', 'Brouwerij Louwaege', 'stout', 'lage', 'zwartbruin', '4,5% vol.'),
(457, 'Louwaege''s pils', 'Brouwerij Louwaege', 'pilsener', 'lage', 'blond EBC 5', '5,0% vol.'),
(458, 'Lowie Kators', 'Brasserie d''Achouffe', 'overige', 'hoge met nof', 'blond', '8,0% vol.'),
(459, 'Lucifer', 'Brouwerij Riva', 'overige', 'hoge', 'blond EBC 7', '8,0% vol.'),
(460, 'Maartsen Tonneke', 'Brouwerij Contreras', 'ale', 'hoge met nof', 'amber', '5,4% vol.'),
(461, 'Madie', 'Brouwerij van Roy', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(462, 'Maes dubbel special', 'Alken-Maes (zetel Waarloos)', '?', '?', '?', 'Onbekend'),
(463, 'Maes pils', 'Alken-Maes (zetel Waarloos)', 'pilsener', 'lage', 'blond EBC 9', '4,9% vol.'),
(464, 'Majutte', 'Brouwerij Strubbe', 'ale', 'hoge', 'amber', '6,0% vol.'),
(465, 'Manneke pils', 'Bouwer Crombé', '?', 'hoge', 'amber', '6,0% vol.'),
(466, 'Maredsous 6 (vat)', 'Brouwerij Moortgat', 'dubbel', 'hoge met nof', 'amber EBC 25', '6,5% vol.'),
(467, 'Maredsous 6° (fles)', 'Brouwerij Moortgat', 'dubbel', 'hoge met nof', 'amber EBC 25', '6,5% vol.'),
(468, 'Maredsous 8 (vat)', 'Brouwerij Moortgat', '?', '?', '?', 'Onbekend'),
(469, 'Maredsous 8° (fles)', 'Brouwerij Moortgat', 'dubbel', 'hoge', 'bruin EBC 50', '8,0% vol.'),
(470, 'Maredsous 9°', 'Brouwerij Moortgat', 'overige', 'hoge met nof', 'bruin EBC 50', '9,0% vol.'),
(471, 'Martens pils', 'Brouwerij Martens', 'pilsener', 'lage', 'blond EBC 8', '5,0% vol.'),
(472, 'Masterbräu', 'Alken-Maes (zetel Alken)', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(473, 'Mc Ewans christmas', 'Lamot (groep Interbrew)', 'overige', 'hoge', 'bruinrood', '8,5% vol.'),
(474, 'Mc Ewans scotch ale', 'Lamot (groep Interbrew)', 'scotch ale', 'hoge', 'roodzwart', '7,2% vol.'),
(475, 'Mechelse bruynen', 'Brouwerij Het Anker', 'overige', 'hoge met nof', 'bruin', '7,0% vol.'),
(476, 'Meister extra lager', 'Brouwerij van Roy', '?', '?', '?', 'Onbekend'),
(477, 'Minty', 'Brouwerij L. Huyghe N.V.', 'overige', 'lage', 'groen', '5,4% vol.'),
(478, 'Moeder Overste', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'amber', '8,0% vol.'),
(479, 'Moinette (blonde)', 'Brasserie Dupont', 'overige', 'hoge met nof', 'licht amber', '8,5% vol.'),
(480, 'Moinette (brune)', 'Brasserie Dupont', 'overige', 'hoge met nof', 'donker amber', '8,5% vol.'),
(481, 'Moinette Athoise', 'Brasserie Dupont', 'overige', 'hoge met nof', 'donker amber', '8,5% vol.'),
(482, 'Monseigneur', 'Brouwerij Bios', 'dubbel', 'hoge met nof', 'donkerbruin', '8,0% vol.'),
(483, 'Monseigneur grand cru', 'Brouwerij Bios', 'overige', 'hoge met nof', 'amber', '8,0% vol.'),
(484, 'Moortgat extra pilsener (fles)', 'Brouwerij Moortgat', 'pilsener', 'lage', 'blond EBC 6', '5,1% vol.'),
(485, 'Moortgat extra pilsener (vat)', 'Brouwerij Moortgat', 'pilsener', 'lage', 'blond EBC 6', '5,1% vol.'),
(486, 'Moriau gueuze', 'Gueuzestekerij Moriau', 'gueuze', 'spontane', 'licht amber', '5,5% vol.'),
(487, 'Moriau kriek', 'Gueuzestekerij Moriau', 'kriekenbier', 'spontane', 'rood', '5,5% vol.'),
(488, 'Mort Subite cassis', 'Brouwerij De Keersmaeker (groep Alken-Maes)', 'cassisbier', 'spontane', 'bruin', '4,0% vol.'),
(489, 'Mort Subite framboise', 'Brouwerij De Keersmaeker (groep Alken-Maes)', 'framboise', 'spontane', 'rood-amber', '4,0% vol.'),
(490, 'Mort Subite gueuze gefilterd', 'Brouwerij De Keersmaeker (groep Alken-Maes)', 'gueuze', 'spontane', 'amber', '5,0% vol.'),
(491, 'Mort Subite gueuze ongefilterd', 'Brouwerij De Keersmaeker (groep Alken-Maes)', 'gueuze', 'spontane nof', 'amber', '6,5% vol.'),
(492, 'Mort Subite kriek', 'Brouwerij De Keersmaeker (groep Alken-Maes)', 'kriekenbier', 'spontane', 'rood', '4,5% vol.'),
(493, 'Munck pils', 'Brouwerij Haacht', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(494, 'Myn''s pils', 'Brasserie de Silly', 'pilsener', 'lage', 'blond', '4,9% vol.'),
(495, 'Napoléon', 'Brouwerij de Smedt', 'overige', 'hoge', 'roodbruin EBC 50', '7,4% vol.'),
(496, 'Ne Flierefluiter', 'Brouwerij de Smedt', 'overige', 'hoge met nof', 'amber EBC 19', '6,5% vol.'),
(497, 'Neyt export', 'Brouwerij Neyt', 'pilsener', 'lage', 'blond EBC 6', '4,7% vol.'),
(498, 'Neyt pils', 'Brouwerij Neyt', 'pilsener', 'lage', 'blond EBC 6', '5,0% vol.'),
(499, 'Noël-christmas-Weihnacht', 'Brouwerij Verhaeghe', 'tripel', 'hoge', 'blond', '7,5% vol.'),
(500, 'NouNou', 'Brouwerij Bios', 'Belgische ale', 'hoge', 'amber', '5,0% vol.'),
(501, 'Odnar', 'Brouwerij Liefmans (groep Riva)', 'Vlaamse bruine', 'hoge', 'donkerbruin', '4,8% vol.'),
(502, 'Oelens boerke', 'Brouwerij Leroy', 'superpils', 'lage', 'blond', '6,5% vol.'),
(503, 'Oeral', 'De Dolle Brouwers', 'overige', 'hoge met nof', 'bruin', '6,0% vol.'),
(504, 'Old Musketeer', 'Brouwerij Leroy', 'overige', 'hoge', 'lichtbruin', '8,0% vol.'),
(505, 'Op-ale', 'Brouwerij de Smedt', 'Belgische ale', 'hoge', 'amber EBC 20', '5,0% vol.'),
(506, 'Ops-ale', 'St. Jozef', 'pilsener', 'lage', 'blond EBC 8', '5,5% vol.'),
(507, 'Oud Hoegaarden', 'Brouwerij De Kluis (groep Interbrew)', 'witbier', '?', '?', 'Onbekend'),
(508, 'Oud Kriekenbier', 'Brouwerij Crombé', 'kriekenbier', 'hoge', 'rood', '6,1% vol.'),
(509, 'Oud Zottegems bier', 'Brouwerij Crombé', 'overige', 'hoge', 'amber', '6,5% vol.'),
(510, 'Oudenaards wit tarwebier', 'Brouwerij Clarysse', 'weizenbier', 'hoge met nof', 'blond', '4,8% vol.');
INSERT INTO `belgisch_bier` (`ID`, `Naam`, `Brouwer`, `Type`, `Gisting`, `Kleur`, `Alcoholperc`) VALUES
(511, 'Palingbier', 'Brouwerij van Roy', 'tripel', 'hoge', 'blond EBC 13', '7,8% vol.'),
(512, 'Pandoer', 'Brouwerij Verhaeghe', 'Vlaamse bruine', 'hoge', 'donkerbruin', '5,8% vol.'),
(513, 'Parel pils', 'Brouwerij van Roy', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(514, 'Pater Lieven', 'Brouwerij van den Bossche', 'Belgische ale', 'hoge', 'licht amber', '5,4% vol.'),
(515, 'Paulus', 'Brouwerij Leroy', 'Vlaamse bruine', 'hoge', 'lichtbruin', '7,0% vol.'),
(516, 'Pauwel Kwak', 'Brouwerij Bosteels', 'gerstewijn', 'hoge', 'roodbruin EBC 40', '8,5% vol.'),
(517, 'Pax pils', 'St. Jozef', 'pilsener', 'lage', 'blond EBC 6', '4,8% vol.'),
(518, 'Pecheresse', 'Brouwerij Lindemans', 'perzikbier', 'spontane', 'blond', '3,6% vol.'),
(519, 'Peeterman', 'Brouwerij De Kluis (groep Interbrew)', 'witbier', 'hoge', 'licht amber', '4,5% vol.'),
(520, 'Perle d''Hastière', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'amber', '8% vol.'),
(521, 'Peter Benoit', 'Brouwerij Leroy', 'overige', 'hoge', 'lichtbruin', '7,0% vol.'),
(522, 'Petrus', 'Bavik - De Brabandere', 'Vlaamse bruine', 'hoge', 'donkerbruin', '5,5% vol.'),
(523, 'Pick-up pils', 'Brouwerij Walrave', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(524, 'Pils', 'Brouwerij Callewaert', 'pilsener', 'lage', 'blond', '5,0% vol.'),
(525, 'Pils', 'Brouwerij Riva', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(526, 'Pils artisanale', 'Brouwerij Lefebvre', 'pilsener', 'lage', 'blond', '5,0% vol.'),
(527, 'Pint''Cousse', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin', '7,4% vol.'),
(528, 'Piraat', 'Brouwerij Bios', 'gerstewijn', 'hoge met nof', 'blond', '11,0% vol.'),
(529, 'Poje', 'Brasserie à Vapeur', 'overige', 'hoge met nof', 'blond', '8,0% vol.'),
(530, 'Polderbier', 'Brouwerij ''t Steedje', 'overige', 'hoge met nof', 'bruin', '9,0% vol.'),
(531, 'Pony stout', 'Bavik - De Brabandere', 'stout', 'lage', 'zwartbruin', '4,9% vol.'),
(532, 'Poorter', 'Brouwerij Sterkens', 'ale', 'hoge', 'donker amber', '6,5% vol.'),
(533, 'Poperings Hommelbier', 'Brouwerij van Eecke', 'overige', 'hoge met nof', 'licht amber', '7,5% vol.'),
(534, 'Postel Abdijbier', 'Brouwerij de Smedt', 'dubbel', 'hoge met nof', 'bruin EBC 60', '6,5% vol.'),
(535, 'Prik pils', 'Brouwerij Roman', 'pilsener', 'lage', 'blond EBC 7', '5,1% vol.'),
(536, 'Primus Haacht pils', 'Brouwerij Haacht', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(537, 'Prisma pils', 'Brouwerij Haacht', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(538, 'Privat', 'Brouwerij Riva', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(539, 'Profi pils', 'Brouwerij van Roy', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(540, 'Prosit pils', 'Brouwerij Bosteels', 'pilsener', 'lage', 'blond EBC 8', '4,8% vol.'),
(541, 'Pruver', 'Brouwerij R. Gielen', 'overige', 'hoge met nof', 'amber', '5,2% vol.'),
(542, 'Punch beer (blond)', 'Brouwerij Facon', 'overige', 'hoge', 'licht amber', '7,5% vol.'),
(543, 'Rafexport', 'Brouwerij Contreras', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(544, 'Redor pils', 'Brasserie Dupont', 'pilsener', 'lage', 'blond', '5,5% vol.'),
(545, 'Reets brooikensbier', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'licht amber', '7,0% vol.'),
(546, 'Reinbräu', 'Alken-Maes (zetel Alken)', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(547, 'Reuzen oud bier', 'Brasserie Dupont', 'overige', 'hoge met nof', 'licht amber', '8,5% vol.'),
(548, 'Régal Christmas', 'Brasserie du Bocq', 'scotch ale', 'hoge met nof', 'bruin EBC 44', '9,0% vol.'),
(549, 'Réserve Marie de Hongrie', 'Brasserie la Binchoise', 'overige', 'hoge met nof', 'bruin', '8,3% vol.'),
(550, 'Rétro oude methode', 'Brouwerij L. Huyghe N.V.', 'ale', 'hoge', 'amber EBC 28', '6,7% vol.'),
(551, 'Rétro pils oude methode', 'Brouwerij L. Huyghe N.V.', 'pilsener', 'lage', 'blond EBC 8', '5,1% vol.'),
(552, 'Rijsels tripel', 'Brouwerij Bios', 'tripel', 'hoge met nof', 'blond', '9,0% vol.'),
(553, 'Riva 2000', 'Brouwerij Riva', 'superpils', 'lage', 'blond EBC 8', '6,1% vol.'),
(554, 'Riva christmas', 'Brouwerij Riva', 'dubbel', 'hoge', 'bruin EBC 50', '8,0% vol.'),
(555, 'Riva pils', 'Brouwerij Riva', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(556, 'Rochefort 6', 'Abbaye Notre Dame De St.Rémy', 'trappist/dubbel', 'hoge met nof', 'bruin', '7,5% vol.'),
(557, 'Rochefort 8', 'Abbaye Notre Dame De St.Rémy', 'trappist/gerstewijn', 'hoge met nof', 'roodbruin', '9,2% vol.'),
(558, 'Rochefort 10', 'Abbaye Notre Dame De St.Rémy', 'trappist/gerstewijn', 'hoge met nof', 'donkerbruin', '11,3% vol.'),
(559, 'Rochus', 'Brouwerij de Ryck', 'overige', 'hoge', 'donkerbruin', '6,2% vol.'),
(560, 'Rodal', 'De Neve (groep Belle-Vue)', 'overige', 'hoge+spontane', 'bruin', '5,0% vol.'),
(561, 'Rodenbach grand cru', 'Bierbrouwerij Rodenbach', 'Vlaamse bruine', 'hoge+melkzure', 'bruin EBC 65', '6,7% vol.'),
(562, 'Roman export', 'Brouwerij Roman', 'pilsener', 'lage', 'blond EBC 7', '5,1% vol.'),
(563, 'Roman Oudenaards', 'Brouwerij Roman', 'Vlaamse bruine', 'hoge', 'bruin EBC 70', '5,0% vol.'),
(564, 'Romy luxe', 'Brouwerij Roman', 'pilsener', 'lage', 'blond EBC 8', '5,6% vol.'),
(565, 'Romy pils', 'Brouwerij Roman', 'pilsener', 'lage', 'blond EBC 7', '5,1% vol.'),
(566, 'Rosé de Cambrinus', 'Brouwerij Cantillon', 'framboise', 'spontane', 'rose', '5,4% vol.'),
(567, 'Royal pils', 'Brouwerij Riva', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(568, 'RUCA pils', 'Brouwerij Isebaert', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(569, 'Safir pils', 'Artois (groep Interbrew)', 'pilsener', 'lage', 'blond', '5,1% vol.'),
(570, 'Saison 1900', 'Brasserie Lefèbvre', 'saison', 'hoge', 'amber', '5,0% vol.'),
(571, 'Saison de Pipaux', 'Brasserie à Vapeur', 'saison', 'hoge met nof', 'amber', '6,5% vol.'),
(572, 'Saison de Silly', 'Brasserie de Silly', 'saison', 'hoge', 'bruin', '5,4% vol.'),
(573, 'Saison Dupont', 'Brasserie Dupont', 'saison', 'hoge met nof', 'blond', '6,5% vol.'),
(574, 'Saison Regal', 'Brasserie du Bocq', 'saison', 'hoge met nof', 'amber EBC 23', '6,1% vol.'),
(575, 'Salvator abdijbier', 'Brouwerij van Roy', 'bokbier', 'hoge', 'bruin EBC 90', '7,3% vol.'),
(576, 'Samwell pils', 'Brouwerij van Roy', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(577, 'Sanctus', 'Brouwerij Moortgat', 'dubbel', 'hoge met nof', 'donkerbruin EBC 70', '6,5% vol.'),
(578, 'Sandersput pils', 'Brouwerij van Roy', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(579, 'Sas export', 'Brouwerij Leroy', 'pilsener', 'lage', 'blond', '5,0% vol.'),
(580, 'Sas pils', 'Brouwerij Leroy', 'pilsener', 'lage', 'blond', '5,0% vol.'),
(581, 'Sasbraü', 'Brouwerij Leroy', 'superpils', 'lage', 'blond', '6,5% vol.'),
(582, 'Satyre', 'Brouwerij de Block', 'dubbel', 'hoge', 'bruin', '8,0% vol.'),
(583, 'Schavuit', 'Brouwerij Callewaert', 'Vlaamse bruine', 'hoge', 'bruin', '8,0% vol.'),
(584, 'Scotch', 'Brasserie de Silly', 'scotch ale', 'hoge', 'donkerbruin', '8,5% vol.'),
(585, 'Sezoens', 'Brouwerij Martens', 'overige', 'hoge', 'blond EBC 9', '6,0% vol.'),
(586, 'Si Boune (blonde)', 'Brasserie du Bocq', 'tripel', 'hoge met nof', 'blond EBC 10', '8,10% vol.'),
(587, 'Si Boune (brune)', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin', '7,4% vol.'),
(588, 'Silbrau dort', 'Brasserie de Silly', 'saison', 'hoge', 'amber', '5,8% vol.'),
(589, 'Silver pils', 'Brouwerij Moortgat', 'pilsener', 'lage', 'blond EBC 6', '5,1% vol.'),
(590, 'Simon Noël', 'Brasserie Simon', 'bokbier', 'lage', 'robijnrood EBC 70', '7,0% vol.'),
(591, 'Simon pils', 'Brasserie Simon', 'pilsener', 'lage', 'blond EBC 9', '4,8% vol.'),
(592, 'Simon Régal', 'Brasserie Simon', 'dortmunder', 'lage', 'blond EBC 10', '5,5% vol.'),
(593, 'Sinaaise bok', 'Brouwerij Bios', 'overige', 'hoge met nof', 'amber', '8,0% vol.'),
(594, 'Ski-rodt biermuseum blonde', 'Brasserie du Bocq', 'overige', 'hoge met nof', 'blond EBC 12', '7,4% vol.'),
(595, 'Ski-rodt biermuseum brune', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin', '7,4% vol.'),
(596, 'Slag lager', 'Brouwerij Slagmuylder', 'dortmunder', 'lage', 'blond EBC 10', '5,5% vol.'),
(597, 'Slaghmuylder kerstbier', 'Brouwerij Slagmuylder', 'dortmunder', 'lage', 'blond EBC 10', '5,5% vol.'),
(598, 'Slaghmuylder paasbier', 'Brouwerij Slagmuylder', 'dortmunder', 'lage', 'blond EBC 10', '5,5% vol.'),
(599, 'Smash', 'Brouwerij Riva', 'tripel', 'hoge', 'amber EBC 23', '8,0% vol.'),
(600, 'Soldaat', 'Brouwerij Sterkens', 'dubbel', 'hoge', 'bruin', '5,5% vol.'),
(601, 'Soleilmont double', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'licht amber', '7,0% vol.'),
(602, 'Soleilmont triple', 'Brasserie de Silly', 'scotch ale', 'hoge', 'donkerbruin', '8,5% vol.'),
(603, 'Sparta pils', 'Brouwerij Bios', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(604, 'Speciaal Natuurbier', 'Brouwerij Strubbe', 'dortmunder', 'lage', 'blond', '4,5% vol.'),
(605, 'Special 6', 'Brouwerij de Block', 'Belgische ale', 'hoge', 'roodbruin', '4,7% vol.'),
(606, 'Special De Ryck', 'Brouwerij de Ryck', 'Belgische ale', 'hoge', 'licht amber', '4,0% vol.'),
(607, 'Special Drink center Shape', 'Brouwerij L. Huyghe N.V.', 'pilsener', 'lage', 'blond EBC 8', '5,1% vol.'),
(608, 'Special Katje', 'Brouwerij Leroy', 'overige', 'hoge', 'bruin', '7,0% vol.'),
(609, 'Special Roman', 'Brouwerij Roman', 'Vlaamse bruine', 'hoge', 'bruin EBC 80', '5,5% vol.'),
(610, 'Speciale Aerts', 'Brouwerij Palm', 'Belgische ale', 'hoge', 'amber EBC 23', '4,8% vol.'),
(611, 'Speciale Palm', 'Brouwerij Palm', 'Belgische ale', 'hoge', 'amber EBC 20', '5,2% vol.'),
(612, 'Speciale Stop', 'Bavik - De Brabandere', 'Belgische ale', 'hoge', 'licht amber EBC 16', '5,0% vol.'),
(613, 'Spéciale de Fourquepire', 'Brasserie Dupont', 'overige', 'hoge met nof', 'licht amber', '8,5% vol.'),
(614, 'Spéciale des Géants', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'amber', '8% vol.'),
(615, 'Spéciale Villers Saint-Ghislain', 'Brasserie de Silly', 'dubbel', 'hoge', 'lichtbruin', '8,0% vol.'),
(616, 'St. André', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'amber', '8% vol.'),
(617, 'St. Benoit blonde', 'Brasserie du Bocq', 'overige', 'hoge met nof', 'blond EBC 12', '7,4% vol.'),
(618, 'St. Benoit brune', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin', '7,4% vol.'),
(619, 'St. Bernardus', 'Brouwerij St. Bernardus', 'dubbel', 'hoge met nof', 'donkerbruin', '7,5% vol.'),
(620, 'St. Denis dark', 'Brouwerij Sterkens', 'ale', 'hoge', 'donker amber', '6,5% vol.'),
(621, 'St. Denise grand cru', 'Brouwerij Sterkens', 'tripel', 'hoge met nof', 'blond', '7,2% vol.'),
(622, 'St. Feuillien (blonde)', 'Brasserie Friart', 'overige', 'hoge met nof', 'amber', '5,5% vol.'),
(623, 'St. Feuillien (blonde)', 'Brasserie du Bocq', 'overige', 'hoge met nof', 'amber', '5,5% vol.'),
(624, 'St. Feuillien (brune)', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin', '7,4% vol.'),
(625, 'St. Feuillien (brune)', 'Brasserie Friart', 'dubbel', 'hoge met nof', 'bruin', '7,4% vol.'),
(626, 'St. Feuillien cuvée de noël', 'Brasserie du Bocq', 'scotch ale', 'hoge met nof', 'bruin EBC 44', '9,0% vol.'),
(627, 'St. Hubert', 'Brasserie de l''Abbaye des Rocs (Brasserie Eloir-Bertiau)', 'overige', 'hoge', 'roodbruin', '6,8% vol.'),
(628, 'St. Laurent', 'Brouwerij Sterkens', 'ale', 'hoge', 'donker amber', '6,5% vol.'),
(629, 'St. Laurent triple', 'Brouwerij Sterkens', 'tripel', 'hoge met nof', 'blond', '7,2% vol.'),
(630, 'St. Léger', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'licht amber', '7,0% vol.'),
(631, 'St. Louis cassis kir royal', 'Brouwerij Van Honsebrouck', 'overige', 'spontane', 'roodbruin', '5,0% vol.'),
(632, 'St. Louis framboisée', 'Brouwerij Van Honsebrouck', 'framboise', 'spontane', 'rood-amber', '5,0% vol.'),
(633, 'St. Louis gueuze lambic', 'Brouwerij Van Honsebrouck', 'gueuze', 'spontane', 'amber', '5,0% vol.'),
(634, 'St. Louis kriek lambic', 'Brouwerij Van Honsebrouck', 'kriekenbier', 'spontane', 'rood', '5,0% vol.'),
(635, 'St. Louis pêche lambic', 'Brouwerij Van Honsebrouck', 'overige', 'spontane', 'oker', '5,0% vol.'),
(636, 'St. Mengold 25cl.', 'Brasserie de Silly', 'dubbel', 'hoge', 'lichtbruin', '8,0% vol.'),
(637, 'St. Mengold Huy', 'Brasserie à Vapeur', 'overige', 'hoge met nof', 'blond', '8,0% vol.'),
(638, 'St. Sebastiaan', 'Brouwerij Sterkens', 'ale', 'hoge', 'donker amber', '6,5% vol.'),
(639, 'St. Sixtus Abdij Abt 12', 'Brouwerij St. Bernardus', 'gerstewijn', 'hoge met nof', 'donkerbruin', '9,5% vol.'),
(640, 'St. Sixtus Abdij Pater 6', 'Brouwerij St. Bernardus', 'dubbel', 'hoge met nof', 'donkerbruin', '6,0% vol.'),
(641, 'St. Sixtus Abdij Prior 8', 'Brouwerij St. Bernardus', 'dubbel', 'hoge met nof', 'donkerbruin', '7,5% vol.'),
(642, 'Steedje special', 'Brouwerij ''t Steedje', 'overige', 'hoge met nof', 'bruin', '8,5% vol.'),
(643, 'Steedje tripel', 'Brouwerij ''t Steedje', 'tripel', 'hoge met nof', 'amber', '8,0% vol.'),
(644, 'Steenezel', 'Brouwerij Bios', 'gerstewijn', 'hoge met nof', 'blond', '11,0% vol.'),
(645, 'Stella Artois', 'Artois (groep Interbrew)', 'pilsener', 'lage', 'blond', '5,1% vol.'),
(646, 'Stille Nacht', 'De Dolle Brouwers', 'gerstewijn', 'hoge met nof', 'bruinrood', '8,0% vol.'),
(647, 'Stoere pils', 'Brouwerij van Roy', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(648, 'Stoeren Bonk', 'Brouwerij Bios', 'overige', 'hoge met nof', 'amber', '6,3% vol.'),
(649, 'Stout', 'Brouwerij Strubbe', 'stout', 'hoge', 'zwartbruin', '5,0% vol.'),
(650, 'Stout Leroy', 'Brouwerij Leroy', 'stout', 'lage', 'zwartbruin', '6,0% vol.'),
(651, 'Stropken', 'Brouwerij Slagmuylder', 'overige', 'hoge met nof', 'lichtbruin', '6,0% vol.'),
(652, 'Strubbe export', 'Brouwerij Strubbe', 'pilsener', 'lage', 'blond', '4,5% vol.'),
(653, 'Sublim', 'Brouwerij Piessens', 'overige', 'hoge met nof', 'blond', '8,5% vol.'),
(654, 'Suna pils', 'Brouwerij Leroy', 'pilsener', 'lage', 'blond', '5,0% vol.'),
(655, 'Super 64', 'Brasserie de Silly', 'Belgische ale', 'hoge', 'amber', '5,2% vol.'),
(656, 'Super des Fagnes', 'Brasserie du Bocq', 'tripel', 'hoge met nof', 'blond EBC 10', '8,10% vol.'),
(657, 'Super Gueuze Cantillon', 'Brouwerij Cantillon', 'gueuze', 'spontane', 'amber', '5,4% vol.'),
(658, 'Super houblo', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'amber', '8% vol.'),
(659, 'Super Lait des Feuilles Mortes', 'Brasserie Dupont', 'overige', 'hoge met nof', 'licht amber', '8,5% vol.'),
(660, 'Super pils', 'Brouwerij Strubbe', 'pilsener', 'lage', 'blond', '4,5% vol.'),
(661, 'Supra pils', 'Artois (groep Interbrew)', 'pilsener', 'lage', 'blond', '5,1% vol.'),
(662, 'Teutenbier', 'Brouwerij van Roy', 'overige', 'hoge met nof', 'licht amber', '7,5% vol.'),
(663, 'Thouroutenaere', 'Brouwerij Louwaege', 'overige', 'hoge met nof', 'blond EBC 9', '8,5% vol.'),
(664, 'Timmermans cassis lambic', 'Brouwerij Timmermans N.V.', 'cassisbier', 'spontane', 'bruin', '5,2% vol.'),
(665, 'Timmermans framboise lambic', 'Brouwerij Timmermans N.V.', 'framboise', 'spontane', 'rood-amber', '5,2% vol.'),
(666, 'Timmermans gueuze caveau', 'Brouwerij Timmermans N.V.', 'gueuze', 'spontane nof', 'amber', '5,2% vol.'),
(667, 'Timmermans gueuze lambic', 'Brouwerij Timmermans N.V.', 'gueuze', 'spontane', 'amber', '5,2% vol.'),
(668, 'Timmermans kriek lambic', 'Brouwerij Timmermans N.V.', 'kriekenbier', 'spontane', 'rood', '5,2% vol.'),
(669, 'Timmermans pêche lambic', 'Brouwerij Timmermans N.V.', 'perzikbier', 'spontane', 'amber', '5,2% vol.'),
(670, 'Tongerlo dubbel', 'St. Guibert (groep Interbrew)', 'dubbel', 'hoge', 'bruin', '6,34% vol.'),
(671, 'Tongerlo Norbertijnerbier', 'St. Guibert (groep Interbrew)', 'dubbel', 'hoge', 'bruin', '6,34% vol.'),
(672, 'Tonneke', 'Brouwerij Contreras', 'Belgische ale', 'hoge', 'amber', '5,0% vol.'),
(673, 'Tradition des Moines blonde', 'Brasserie du Bocq', 'overige', 'hoge met nof', 'blond EBC 12', '7,4% vol.'),
(674, 'Tradition des Moines brune', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin', '7,4% vol.'),
(675, 'Travelling', 'Brasserie du Bocq', 'overige', 'hoge met nof', 'blond EBC 12', '7,4% vol.'),
(676, 'Triple', 'Brouwerij Riva', 'tripel', 'hoge', 'amber EBC 23', '7,6% vol.'),
(677, 'Triple Abbaye d''Aulne', 'Brouwerij de Smedt', 'tripel', 'hoge met nof', 'blond EBC 13', '9,0% vol.'),
(678, 'Triple Aulne', 'Brouwerij de Smedt', 'tripel', 'hoge met nof', 'blond EBC 13', '7,5% vol.'),
(679, 'Triple de Val-Dieu', 'Brouwerij Van Honsebrouck', 'tripel', 'hoge met nof', 'blond', '9,0% vol.'),
(680, 'Triple Moine', 'Brasserie du Bocq', 'tripel', 'hoge met nof', 'blond EBC 10', '8,10% vol.'),
(681, 'Triple Petrus', 'Bavik - De Brabandere', 'tripel', 'hoge', 'licht amber EBC 16', '7,5% vol.'),
(682, 'Triple saison Roland', 'Brasserie Lefèbvre', 'saison', 'hoge', 'amber', '5,0% vol.'),
(683, 'Triple Soleilmont', 'Brasserie de Silly', 'dubbel', 'hoge', 'lichtbruin', '8,0% vol.'),
(684, 'Triple St. Pierre', 'Brasserie Dupont', 'overige', 'hoge met nof', 'licht amber', '8,5% vol.'),
(685, 'Triple Toison d''or', 'Brouwerij Het Anker', 'tripel', 'hoge met nof', 'blond', '7,0% vol.'),
(686, 'Triple Villers', 'Brouwerij Vieille Villers', 'tripel', 'hoge', 'blond', '6,5% vol.'),
(687, 'Trippel Bornem', 'Brouwerij Bios', 'tripel', 'hoge met nof', 'blond', '9,0% vol.'),
(688, 'Ulricher lager', 'Brouwerij Girardin', 'pilsener', 'lage', 'blond', '5,0% vol.'),
(689, 'Upper 19', 'Brouwerij van Roy', 'tripel', 'hoge', 'blond EBC 13', '7,8% vol.'),
(690, 'V Keute di Nameur blonde', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'licht amber', '7,0% vol.'),
(691, 'Vaartlander', 'Brouwerij Bios', 'tripel', 'hoge met nof', 'blond', '9,0% vol.'),
(692, 'Val d''heure (blonde, 25 cl.)', 'Brasserie du Bocq', 'saison', 'hoge met nof', 'amber EBC 23', '6,1% vol.'),
(693, 'Val d''heure (blonde, 75 cl.)', 'Brasserie du Bocq', 'tripel', 'hoge met nof', 'blond EBC 10', '8,1% vol.'),
(694, 'Val d''Heure (brune, 25 cl.)', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin', '7,4% vol.'),
(695, 'Val d''Heure (brune, 75 cl.)', 'Brasserie du Bocq', 'dubbel', 'hoge met nof', 'bruin EBC 44', '8,8% vol.'),
(696, 'Val-Dieu triple', 'Brouwerij Van Honsebrouck', 'tripel', 'hoge met nof', 'blond', '9,0% vol.'),
(697, 'Van der Ghinste''s Tripel', 'Brouwerij Bockor', 'Vlaamse bruine', 'hoge+melkzure', 'bruin', '5,5% vol.'),
(698, 'vander Linden lambik', 'Brouwerij Vander Linden', 'lambic', 'spontane', 'amber', '5,5% vol.'),
(699, 'Vedett', 'Brouwerij Moortgat', 'pilsener', 'lage', 'blond EBC 6', '5,1% vol.'),
(700, 'Vera pils', 'Brouwerij Verhaeghe', 'pilsener', 'lage', 'blond', '4,0% vol.'),
(701, 'Verabraü super pils', 'Brouwerij Verhaeghe', 'pilsener', 'lage', 'blond', '4,0% vol.'),
(702, 'Verabraü urtyp', 'Brouwerij Verhaeghe', 'pilsener', 'lage', 'blond', '4,5% vol.'),
(703, 'Verhaeghe export', 'Brouwerij Verhaeghe', 'pilsener', 'lage', 'blond', '4,0% vol.'),
(704, 'Vichtenaar', 'Brouwerij Verhaeghe', 'Vlaamse bruine', 'hoge', 'donkerbruin', '5,8% vol.'),
(705, 'Vieille des Estinnes', 'Brasserie Dupont', 'overige', 'hoge met nof', 'amber', '7,5% vol.'),
(706, 'Vieille Villers', 'Brouwerij Vieille Villers', 'dubbel', 'hoge', 'donkerbruin', '6,2% vol.'),
(707, 'Vieux Bruges gueuze lambic', 'Brouwerij Van Honsebrouck', 'gueuze', 'spontane', 'amber', '5,0% vol.'),
(708, 'Vieux Bruges framboisée', 'Brouwerij Van Honsebrouck', 'framboise', 'spontane', 'rood-amber', '5,0% vol.'),
(709, 'Vieux Bruges gueuze lambic', 'Brouwerij Van Honsebrouck', 'gueuze', 'spontane', 'amber', '5,0% vol.'),
(710, 'Vieux Bruges kriek lambic', 'Brouwerij Van Honsebrouck', 'kriekenbier', 'spontane', 'rood', '5,0% vol.'),
(711, 'Vieux Temps', 'St. Guibert (groep Interbrew)', 'Belgische ale', 'hoge', 'amber', '5,2% vol.'),
(712, 'Villers tripel', 'Brouwerij Vieille Villers', 'overige', 'hoge', 'blond', '6,9% vol.'),
(713, 'Vlaske', 'Brouwerij de Block', 'overige', 'hoge', 'donker amber', '6,4% vol.'),
(714, 'Voisin saison', 'Brasserie Voisin', 'saison', 'hoge', 'licht amber', '5,5% vol.'),
(715, 'Voisin super', 'Brasserie Voisin', 'Belgische ale', 'hoge', 'amber', '5,2% vol.'),
(716, 'Vondel', 'Brouwerij Riva', 'tripel', 'hoge', 'amber EBC 23', '8,0% vol.'),
(717, 'Walrave export', 'Brouwerij Walrave', 'pilsener', 'lage', 'blond', '4,8% vol.'),
(718, 'Watneys pale ale', 'Union (groep Alken-Maes)', 'pale ale', 'hoge', 'amber EBC 22', '5,4% vol.'),
(719, 'Watneys red', 'Union (groep Alken-Maes)', 'ale', 'hoge', 'amber EBC 28', '5,6% vol.'),
(720, 'Watneys scotch', 'Union (groep Alken-Maes)', 'scotch ale', 'hoge', 'donkerbruin EBC 80', '7,7% vol.'),
(721, 'Watou''s wit bier', 'Brouwerij van Eecke', 'weizenbier', 'hoge met nof', 'blond', '5,0% vol.'),
(722, 'Wellington red lion', 'Union (groep Alken-Maes)', 'ale', 'hoge', 'amber EBC 28', '5,6% vol.'),
(723, 'Wellington scotch ale', 'Union (groep Alken-Maes)', 'dubbel', 'hoge', 'donkerbruin EBC 70', '6,0% vol.'),
(724, 'West pils', 'Brouwerij Leroy', 'pilsener', 'lage', 'blond', '5,0% vol.'),
(725, 'Westmalle tripel', 'Abdij der Trappisten van Westmalle', 'trappist/dubbel', '?', '?', 'Onbekend'),
(726, 'Westmalle dubbel', 'Abdij der Trappisten van Westmalle', '?', '?', '?', 'Onbekend'),
(727, 'Westmalle extra', 'Abdij der Trappisten van Westmalle', 'trappist/tripel', 'hoge met nof', 'oranjegeel EBC 13', '9,00% vol.'),
(728, 'Westvleteren extra 8', 'Abdij St. Sixtus', 'trappist/gerstewijn', 'hoge met nof', 'donkerbruin', '11,3% vol.'),
(729, 'Westvleteren abt 12', 'Abdij St. Sixtus', 'trappist/dubbel', 'hoge met nof', 'donkerbruin', '8,0% vol.'),
(730, 'Westvleteren special 6', 'Abdij St. Sixtus', 'trappist/dubbel', 'hoge met nof', 'donkerbruin', '6,0% vol.'),
(731, 'Wets gueuze', 'Gueuzestekerij Wets', 'gueuze', 'spontane', 'amber', '5,5% vol.'),
(732, 'Wets kriek', 'Gueuzestekerij Wets', 'kriekenbier', 'spontane', 'rood', '6,0% vol.'),
(733, 'Whitbread extra stout', 'Martinas (groep Interbrew)', 'stout', 'hoge', 'zwartbruin', '5,3% vol.'),
(734, 'Whitbread pale ale', 'Martinas (groep Interbrew)', 'pale ale', 'hoge', 'blond', '5,6% vol.'),
(735, 'Wiel''s pils', 'Wielemans', 'pilsener', 'lage', 'blond', '5,0% vol.'),
(736, 'Wiels pils', 'Artois (groep Interbrew)', 'pilsener', 'lage', 'blond', '5,1% vol.'),
(737, 'Wieze christmas', 'Brouwerij van Roy', 'bokbier', 'hoge', 'bruin EBC 90', '7,3% vol.'),
(738, 'Wieze pils', 'Brouwerij van Roy', 'pilsener', 'lage', 'blond EBC 7', '5,0% vol.'),
(739, 'Wilson mild stout', 'Brouwerij Bios', 'stout', 'lage', 'zwartbruin EBC 7', '5,0% vol.'),
(740, 'Witkap pater dubbele pater', 'Brouwerij Slagmuylder', 'dubbel', 'hoge met nof', 'donkerbruin', '7,4% vol.'),
(741, 'Witkap pater stimulo', 'Brouwerij Slagmuylder', 'overige', 'hoge met nof', 'blond', '6,2% vol.'),
(742, 'Witkap pater tripel', 'Brouwerij Slagmuylder', 'tripel', 'hoge met nof', 'blond', '7,6% vol.'),
(743, 'Witte blonde kuif', 'Brouwerij Clarysse', 'weizenbier', 'hoge met nof', 'blond', '4,8% vol.'),
(744, 'Wittekop', 'Brouwerij Riva', 'witbier', 'hoge met nof', 'blond EBC 5', '5,0% vol.'),
(745, 'Wonderbier', 'Brouwerij Moortgat', 'pilsener', 'lage', 'blond EBC 6', '5,1% vol.'),
(746, 'Zafke 25cl.', 'Brasserie Lefèbvre', 'overige', 'hoge met nof', 'licht amber', '7,0% vol.'),
(747, 'Zedelgemse Martelaar', 'Brouwerij Strubbe', 'ale', 'hoge', 'amber', '6,0% vol.'),
(748, 'Zerewever', 'Brouwerij Verhaeghe', 'overige', 'hoge', 'licht amber', '6,0% vol.'),
(749, 'Zottegems bruin', 'Brouwerij Crombé', 'overige', 'hoge', 'bruin', '4,5% vol.'),
(750, 'Zulte', 'Brouwerij van Zulte', 'Vlaamse bruine', 'hoge', 'donkerbruin EBC 85', '5,0% vol.');